### PR TITLE
Sidekick publish button updates

### PR DESCRIPTION
**Pull request by rgclayton**
* Moved the publish button to right side of the sidekick to help avoid accidentally clicking.
* Added a warning pop up message on hover.

Resolves: [MWPW-146126](https://jira.corp.adobe.com/browse/MWPW-146126)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off
- After: https://sidekick-publish-alt--milo--adobecom.hlx.page/drafts/rclayton/test-template?martech=off

image

### CODE REVIEW

**Review by elan-tbx — APPROVED** [review]

**Review by elan-tbx — COMMENTED** [review]
There's about a 3-second delay before the styles get applied to the Publish button on my end... is that to be expected?

**Review by sukamat — COMMENTED** [review]
I see the same behavior that @elan-tbx mentioned about the delay. I also did a shift+refresh after the first load and it went back to the original sidekick layout. I did this in incognito. Not sure if it is just me.

**Comment by rgclayton** [comment]
> I see the same behavior that @elan-tbx mentioned about the delay. I also did a shift+refresh after the first load and it went back to the original sidekick layout. I did this in incognito. Not sure if it is just me.

We have to wait for the sidekick to load, so there can be a slight delay due to that.

There was a recent request to only move the publish button to sit just after the tools button. Doing some testing locally and this helps the appearance delay. 

cc: @elan-tbx @sukamat

**Review by Sartxi — APPROVED** [review]
I don't get the delay at all, but I do have it revert back to the old layout after a page refresh.

**Review by sukamat — APPROVED** [review]
Yea, it seems to be much faster today :shrug:
But the revert-to-old-layout after refresh issue still exists.

**Pull request merged**
