### PR TITLE
MWPW-147027: CTA flowing out of mini compare card (due to long strings)

### PR DESCRIPTION
**Pull request by Axelcureno**
Resolves: MWPW-147027

Fixes alignment of footer CTAs in Mini compare chart merch card when length of content is bigger than card width.

Resolves: [MWPW-147027](https://jira.corp.adobe.com/browse/MWPW-147027)

Test URL: https://main--cc--adobecom.hlx.live/eg_ar/products/illustrator?milolibs=MWPW-147027--milo--adobecom&martech=off
**Before**
Screenshot 2024-04-28 at 10 18 34 PM

**After**
Screenshot 2024-04-28 at 10 18 23 PM

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://MWPW-147027--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by mokimo — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]
Hey @Axelcureno! I see you have a link with `milolibs=local` in the description, that might need to be updated. The issue is not reproducible on the kitchen sink links, the `eg_ar` one is more relevant in this situation. I did manually check there and the issue seems to be fixed, but other reviewers should not need to do this themselves.

**Review by Roycethan — CHANGES_REQUESTED** [review]
Hi @Axelcureno 
1) Can you plz look at this CTA alignment on Tablet viewport:
https://main--cc--adobecom.hlx.live/eg_ar/products/illustrator?milolibs=MWPW-147027--milo--adobecom&martech=off
https://main--cc--adobecom.hlx.page/cz/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off
image

2) Also its better to address the banner overlapping issue across;
https://main--cc--adobecom.hlx.page/cz/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off
image

**Comment by Axelcureno** [comment]
> Hi @Axelcureno
> 
> 1. Can you plz look at this CTA alignment on
>    Tablet viewport:
>    https://main--cc--adobecom.hlx.live/eg_ar/products/illustrator?milolibs=MWPW-147027--milo--adobecom&martech=off
>    https://main--cc--adobecom.hlx.page/cz/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off
> 
> image
> Mobile viewport: https://main--cc--adobecom.hlx.live/jp/products/illustrator?milolibs=MWPW-147027--milo--adobecom&martech=off# image
> 
> 2. Also its better to address the banner overlapping issue across;
>    https://main--cc--adobecom.hlx.page/cz/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off
> 
> image

I have fixed the reported footer issues @Roycethan, please check again 🙏🏼
As discussed, we will tackle the badge overlapping issue in a separate ticket until Consonant provides direction for the fix.

**Review by Roycethan — CHANGES_REQUESTED** [review]
@Axelcureno Ipad view is better now , but mobile view is still disturbed
1) CTA are mis-aligned
2) No left padding for some and they touch border
https://main--cc--adobecom.hlx.page/cz/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off
image

**Review by Roycethan — CHANGES_REQUESTED** [review]
1)https://main--cc--adobecom.hlx.page/ua/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off#
image

2)https://main--cc--adobecom.hlx.page/gr_el/creativecloud?milolibs=MWPW-147027--milo--adobecom&martech=off#
image

**Comment by Axelcureno** [comment]
@Roycethan fixed the last observation, ready for testing.

**Review by Roycethan — APPROVED** [review]
Reported issues are fixed. Thanks @Axelcureno

**Pull request merged**
