### PR TITLE
adding auth token for helpx to run-nala.yml

### PR DESCRIPTION
**Pull request by ancysr**
* Add your
* Specific
* Features or fixes

Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://<branch>--milo--adobecom.hlx.page/?martech=off

### CODE REVIEW

**Comment by mokimo** [comment]
Please read https://github.com/orgs/adobecom/discussions/997

**Review by amauch-adobe — APPROVED** [review]
Approved

**Review by amauch-adobe — COMMENTED** [review]
Hi Ancy, I apologize but I accidentally steered you in the wrong direction.  I just grouped with Santosh and found out that how Nala currently runs on PRs for the Milo repository is slightly different than what I had originally supposed.  How it currently stands is only tests under the tests/milo/ directory in the Nala repository will run on PRs by default.  That being the case you will not need to add the authToken to the GitHub actions yaml for the Milo repository since the helpx test will not get executed where it is not located in the milo test directory under Nala.  Feel free to close your PR on the Milo repo since it is not needed.

Thanks though for being thorough.

**Comment by amauch-adobe** [comment]
@skumar09 and @ancysr we are closing this PR per our comments above.

**Pull request closed without merging**
