### PR TITLE
[MWPW-131397] Unset min-height on Aside background image for notification variant

### PR DESCRIPTION
**Pull request by elan-tbx**
* The base style for the aside block's background image has a min-height of 700px. However, this is undesirable in the notification variant of the aside block, as detailed in the JIRA ticket below. This PR adds a subsequent style rule that unsets this min-height for the notification variant.

Resolves: [MWPW-131397](https://jira.corp.adobe.com/browse/MWPW-131397)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/klee/my-doc?martech=off
- After: https://ebartholomew-aside-bg-image-fix--milo--adobecom.hlx.page/drafts/klee/my-doc?martech=off

### CODE REVIEW

**Comment by mokimo** [comment]
@elan-tbx this does not seem correct yet 
Screenshot 2023-05-24 at 06 03 41

**Comment by narcis-radu** [comment]
@mokimo - are you expecting for the content to fit within the rectangle? I do see some changes compared to a notification without background image - https://main--milo--adobecom.hlx.page/drafts/sarchibeque/notification-centering?martech=off - but not sure whether the content is supposed to fit the rectangle.

**Comment by mokimo** [comment]
@narcis-radu according to the ticket this PR looks correct - on first view the feature looks broken to me 🤷

**Comment by elan-tbx** [comment]
@mokimo @narcis-radu sorry for the confusion, that specific background image maybe isn't the most helpful. I just used the reporter's example page to show that the expected result (shown in the JIRA ticket) is indeed achieved with this PR. Basically, aside notifications just need an exception so their backgrounds aren't set to a minimum of 700px height.

**Review by narcis-radu — APPROVED** [review]

**Review by mokimo — APPROVED** [review]

**Review by honstar — APPROVED** [review]

**Pull request merged**
