### PR TITLE
MWPW-140862: Updated twitter logo

### PR DESCRIPTION
**Pull request by robert-bogos**
## Description
This PR updates the twitter logo.

## Related Issue
Resolves: [MWPW-140862](https://jira.corp.adobe.com/browse/MWPW-140862)

## Screenshots (if appropriate):
Screenshot 2024-01-04 at 14 36 04

## Test URLs
**Acrobat:**
- Before: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off
- After: https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=mwpw-140862-update-twitter-logo--milo--robert-bogos

**BACOM:**
- Before: https://main--bacom--adobecom.hlx.page/products/real-time-customer-data-platform/rtcdp?martech=off
- After: https://main--bacom--adobecom.hlx.page/products/real-time-customer-data-platform/rtcdp?martech=off&milolibs=mwpw-140862-update-twitter-logo--milo--robert-bogos

**CC:**
- Before: https://main--cc--adobecom.hlx.page/?martech=off
- After: https://main--cc--adobecom.hlx.page/?martech=off&milolibs=mwpw-140862-update-twitter-logo--milo--robert-bogos

**Homepage:**
- Before: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off
- After: https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off&milolibs=mwpw-140862-update-twitter-logo--milo--robert-bogos

**Blog:**
- Before: https://main--blog--adobecom.hlx.page/
- After: https://main--blog--adobecom.hlx.page/?milolibs=mwpw-140862-update-twitter-logo--milo--robert-bogos

**Milo:**
- Before: https://main--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off
- After: https://mwpw-140862-update-twitter-logo--milo--robert-bogos.hlx.page/drafts/rbogos/page-default?martech=off

### CODE REVIEW

**Review by mokimo — APPROVED** [review]

**Comment by overmyheadandbody** [comment]
Based on conversations with @robert-bogos, I started a Slack thread to see whether we can get the icon closer to the other logos we use. Depending on the outcome, we might have to update the SVG

| Current | Suggestion |
| ------------- | ------------- |
| Screenshot 2024-01-04 at 15 27 39 | Screenshot 2024-01-04 at 15 29 06 |

**Review by overmyheadandbody — APPROVED** [review]
We'll need a follow-up story for the hollow logo

**Review by SilviuLCF — APPROVED** [review]
Verified , testing details can be found on comments of 
https://jira.corp.adobe.com/browse/MWPW-140862

**Comment by overmyheadandbody** [comment]
Follow up story has been created and can be found at https://jira.corp.adobe.com/browse/MWPW-140953.

I'll be merging this for now.

**Pull request merged**
