### PR TITLE
[Release] Stage to Main

### PR DESCRIPTION
**Pull request by Ruchika4**
- https://github.com/adobecom/milo/pull/2178
- https://github.com/adobecom/milo/pull/2093
- https://github.com/adobecom/milo/pull/2181

### CODE REVIEW

**Review by JackySun9 — APPROVED** [review]

**Review by Sartxi — APPROVED** [review]

**Review by Dli3 — APPROVED** [review]

**Review by tedAir — APPROVED** [review]

**Comment by Ruchika4** [comment]
@Roycethan @JackySun9 @tedAir @Dli3 @sigadamvenkata 
PR https://github.com/adobecom/milo/pull/2181 got merged to stage before this already approved PR could get merged in main because of an urgent issue on production.  This just reverts the code merged in PR https://github.com/adobecom/milo/pull/2059

Could you please help do a quick round of check again.

cc @Blainegunn  @ryanmparrish @rgclayton @narcis-radu @drashti1712 @3ch023

**Comment by Roycethan** [comment]
> @Roycethan @JackySun9 @tedAir @Dli3 @sigadamvenkata PR #2181 got merged to stage before this already approved PR could get merged in main because of an urgent issue on production. This just reverts the code merged in PR #2059
> 
> Could you please help do a quick round of check again.
> 
> cc @Blainegunn @ryanmparrish @rgclayton @narcis-radu @drashti1712 @3ch023

ok re-verified on stage - apart from an issue (causing due to a CDN change ) but not related to this PR , ok from home page side.
For everyone's reference marking here: https://jira.corp.adobe.com/browse/WPS-25099?focusedCommentId=41296503&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-41296503

**Review by JackySun9 — APPROVED** [review]

**Comment by drashti1712** [comment]
Adding `do-not-merge` as another PR merged to stage(https://github.com/adobecom/milo/pull/2123) has been added to this. We might need to revert the stage PR or re-verify the changes on this one. Waiting for confirmation on the same.
@salonijain3 @overmyheadandbody @Blainegunn @Ruchika4

**Comment by salonijain3** [comment]
`Do not merge` label has been removed, as the other PR on stage has been reverted and will be raised after this PR goes to main as per the process.

**Review by sigadamvenkata — APPROVED** [review]

**Pull request merged**
