### PR TITLE
[MWPW-142899] Add additional IMS scopes for Universal Navigation integration

### PR DESCRIPTION
**Pull request by narcis-radu**
The Universal Navigation uses additional IMS scopes to render user data (avatar and firefly credits balance). Adding the additional scope will ensure that the Profile Menu is rendered correctly when the Universal Navigation is enabled.
Note: all known IMS client IDs from the list - https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=adobedotcom&title=Adobe.com+IMS+Client+IDs -  have been previously granted access for these additional IMS scopes.

Resolves: [MWPW-142899](https://jira.corp.adobe.com/browse/MWPW-142899)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/narcis/default?martech=off
- After: https://gnav--milo--adobecom.hlx.page/drafts/narcis/default?martech=off

Milo consumers
- DC - https://www.stage.adobe.com/acrobat/online/sign-pdf.html?martech=off&milolibs=gnav--milo--adobecom
- BACOM - https://business.stage.adobe.com/fr/customer-success-stories.html?milolibs=gnav--milo--adobecom
- CC - https://main--cc--adobecom.hlx.live/?martech=off&milolibs=gnav--milo--adobecom
- Homepage - https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?martech=off&milolibs=gnav--milo--adobecom
- Blog - https://main--blog--adobecom.hlx.page/?milolibs=gnav--milo--adobecom

### CODE REVIEW

**Review by mokimo — APPROVED** [review]

**Comment by mokimo** [comment]
Should we change the description to something more actionable, since each consumer will need to add those scopes to their scripts/ims configs too?

**Comment by narcis-radu** [comment]
@mokimo - I checked existing Milo projects and they inherit the scope configuration from Milo. However, the integration wiki will account for this step, all consumers are required to add the additional scope - https://wiki.corp.adobe.com/display/adobedotcom/Universal+Navigation+integration+guide

**Review by overmyheadandbody — APPROVED** [review]

**Review by robert-bogos — APPROVED** [review]

**Comment by overmyheadandbody** [comment]
> a small addition to ensure that the same default scope is set if not able to retrieve from config

That was going to be my next suggestion, great that it's already in!

**Review by mokimo — APPROVED** [review]

**Comment by narcis-radu** [comment]
> Since not including those scopes leads to users not being able to sign in
One more note on this: not including the scopes in the configuration will not break the sign in functionality. The functionality is broken when the scopes are included in the config, but they are not approved in IMSS. I have manually checked all IMS client IDs and all have been granted the scopes.

**Review by honstar — APPROVED** [review]

**Pull request merged**
