### PR TITLE
MWPW-131002 - SKMS integration

### PR DESCRIPTION
**Pull request by amauch-adobe**
- Adds auto-approved CMR integration on Milo releases for SKMS.
- New GitHub action for merged pull requests against the production branch.

Resolves: [MWPW-131002](https://jira.corp.adobe.com/browse/MWPW-131002)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://skms-integration--milo--amauch-adobe.hlx.page/?martech=off

See [here](https://wiki.corp.adobe.com/pages/viewpage.action?pageId=3014303185) for instructions on how to test this integration. Specifically, read my comment at the bottom in the "Comments".

### CODE REVIEW

**Comment by amauch-adobe** [comment]
See [here](https://wiki.corp.adobe.com/pages/viewpage.action?pageId=3014303185) for instructions on how to test this integration.

**Comment by amauch-adobe** [comment]
Tested on my forked branch [here](https://github.com/amauch-adobe/milo/actions/runs/6580533901). See screenshots below from the SKMS system as well GitHub actions workflow run:

GitHub Action Job Result:
 
Screenshot 2023-10-19 at 3 52 34 PM

SKMS System CMR Created:

Screenshot 2023-10-19 at 3 44 42 PM

**Comment by auniverseaway** [comment]
@amauch-adobe any update on this? Can this be merged?

**Comment by amauch-adobe** [comment]
> @amauch-adobe any update on this? Can this be merged?

Yes, this can be merged, was just waiting for reviews.  I was going to ping out to the channel today to see if I couldn't get any eyes on it.

**Pull request closed without merging**
