### PR TITLE
MWPW-142961 - Support video in split marquee foreground

### PR DESCRIPTION
**Pull request by elan-tbx**
* Split marquees have the option to add a media caption to the foreground content -- however, this feature erroneously pulled videos into the caption area, because videos begin as simple links on the document. This PR adds an exception for text that contains "http...mp4"
* This PR also splits the...split marquee decoration into its own function.
* A style tweak was also applied so video elements don't get squished in the foreground.

Resolves: [MWPW-142961](https://jira.corp.adobe.com/browse/MWPW-142961)

**Test URLs:**
Milo:
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/marquee-split?martech=off
- After: https://ebartholomew-MWPW-142961-mq-split-video--milo--adobecom.hlx.page/docs/library/kitchen-sink/marquee-split?martech=off

CC:
- Before: https://main--cc--adobecom.hlx.page/drafts/00-CC-milo-migration/bugs/document?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/00-CC-milo-migration/bugs/document?martech=off&milolibs=ebartholomew-MWPW-142961-mq-split-video

### CODE REVIEW

**Review by ryanmparrish — APPROVED** [review]
Looks good. 
The first 'after' link looks to have a `?milolibs=local` in the path. 
I'm guessing that isn't meant to be there?

**Review by Sartxi — APPROVED** [review]
LGTM

**Comment by elan-tbx** [comment]
@ryanmparrish Welp, that's embarrassing 😅 thanks for catching that

**Comment by mokimo** [comment]
I have no idea how github comes up with those changes, you may want to rebase your initial PR back onto stage https://github.com/adobecom/milo/commit/6a7572a725dc4d5e2026fe575e04daef86edbd1b ... sorry for the force push!

**Pull request merged**
