### PR TITLE
MWPW-123760

### PR DESCRIPTION
**Pull request by Blainegunn**
This was a request to have .svg lazy loaded.

Resolves: [MWPW-123760](https://jira.corp.adobe.com/browse/MWPW-123760)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://lazy-svg--milo--adobecom.hlx.page/?martech=off

### CODE REVIEW

**Comment by rgclayton** [comment]
I created a test page for you to  see this in action - I'm a visual person :)

https://lazy-svg--milo--adobecom.hlx.page/drafts/rclayton/test-svg

Is it intended that the `.svg` be turned into a link with this update?

**Comment by rgclayton** [comment]
I'm guessing the `.svg` is getting wrapped in an `<a>` in my example page due to new functionality added to Franklin that now allows svgs to be sourced from Sharepoint?

**Comment by vhargrave** [comment]
> I'm guessing the `.svg` is getting wrapped in an `<a>` in my example page due to new functionality added to Franklin that now allows svgs to be sourced from Sharepoint?

@rgclayton I'd guess that too. 👍

**Review by vhargrave — COMMENTED** [review]
unit tests need to be fixed and then it's good for me.

**Review by rgclayton — APPROVED** [review]

**Review by rgclayton — APPROVED** [review]

**Review by chrischrischris — APPROVED** [review]

**Review by chrischrischris — DISMISSED** [review]
tests need to be fixed/updated

**Comment by rgclayton** [comment]
Unit tests look good now after merging main in.

**Review by vhargrave — APPROVED** [review]

**Review by auniverseaway — APPROVED** [review]

**Comment by auniverseaway** [comment]
Verified:
Lazy attribute exists on all image elements.

**Pull request merged**
