### PR TITLE
MWPW-161170: Multiple UI CCD Slice/suggested merch card fixes

### PR DESCRIPTION
**Pull request by Axelcureno**
This PR contains multiple UI fixes, including:

- CCD Slice/Suggested card Spectrum border color.
- Dynamic mnemonic size based on card variant (Slice using M, Suggested using L).
- Max-width and max-height defined for Slice/Suggested cards.
- Corrected CCD Slice/Suggested badge alignment/font style.
- Reduced gap between icon and badge to 8px (was 16px).

Resolves: [MWPW-161170](https://jira.corp.adobe.com/browse/MWPW-161170)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-161170--milo--adobecom.hlx.live/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by yesil — APPROVED** [review]

**Review by npeltier — APPROVED** [review]

**Comment by Roycethan** [comment]
@Axelcureno 
On a quick glance the padding below the CTA's seem to be off on the cards, plz check thanks
image

**Comment by Axelcureno** [comment]
> @Axelcureno On a quick glance the padding below the CTA's seem to be off on the cards, plz check thanks image

@Roycethan this particular one is fixed in @yesil's PR: https://ccd--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?theme=dark&martech=off

**Comment by Roycethan** [comment]
@Axelcureno  Regression done on consuming apps. Testing on CCD is TBD yet....
Can you plz fix the aem-psi-check failure meanwhile, 
Also i think it would be better if Ilyas's PR goes to stage and then this one since like fix for issues (in his branch)above can be  
included in this PR to avoid any conflicts.

**Comment by yesil** [comment]
@Axelcureno it looks like mas.js is not build in your PR.

**Comment by Axelcureno** [comment]
> @Axelcureno it looks like mas.js is not build in your PR.

@yesil thanks, added.

**Comment by Roycethan** [comment]
> @Axelcureno On a quick glance the padding below the CTA's seem to be off on the cards, plz check thanks image

Fixed after Max-height is removed..

**Comment by Roycethan** [comment]
Fixes looks fine now... the one which mentioned in ticket which is not touched is :
Background color is not matching with other cards on CCD Apps panel. - @Axelcureno  left a comment on the same in ticket: https://jira.corp.adobe.com/browse/MWPW-161170

**Comment by Roycethan** [comment]
@Axelcureno 
 On suggested cards -
1)Body text looks bit dull 
Body text : 
Figma: Body S (14pt) Grey 800 (#222222)
Gallary:  Grey 700 #464646
image

2)CTA button text color: figma: #464646 instead of #222222 in gallary

3) Content box dimensions:
Figma: width: 265px;
height: 165px;
top: 20px;
left: 20px;
gap: 16px;
opacity: 0px;

Gallary: 263*163 padding-right is 19px  - atleast here right padding needs to be consistent
image.png

**Comment by afmicka** [comment]
@Axelcureno @Roycethan 

On suggested card:
1. the padding bellow CTAs is not consistent. On their examples, cards with 4 rows fit in a smaller content frame and CTAs are on the same position in all cards. 
gallery: 
kSAkB

figma: 
Screenshot 2024-11-13 at 15 26 58

2. The CTA border and text color should be grey 700, not 800 (request in the jira as well) 

3. they have a request in the jira `increase space between eyebrow text and headline text from 0px to 2px`. I don't see that gapping but maybe i am not looking right
Screenshot 2024-11-13 at 11 12 52

4. When the font is not loaded, CTA gets outside the card (probably the text would do the same) and card does not expand. On main, everything stays within the card as the card expands

branch: 
Screenshot 2024-11-13 at 10 50 23

main: 
Screenshot 2024-11-13 at 15 22 47

**Comment by Roycethan** [comment]
@Axelcureno  In your branch the description is not visible  on this merch card:
https://main--cc--adobecom.hlx.live/products/illustrator/campaign/pricing?milolibs=mwpw-161170--milo--adobecom
image

**Comment by Roycethan** [comment]
> @Axelcureno In your branch the description is not visible on this merch card: https://main--cc--adobecom.hlx.live/products/illustrator/campaign/pricing?milolibs=mwpw-161170--milo--adobecom image

Fixed

**Pull request merged**
