### PR TITLE
Fix video CLS netting +10 lighthouse points

### PR DESCRIPTION
**Pull request by mokimo**
Original PR: https://github.com/adobecom/milo/pull/2724
Revert PR: https://github.com/adobecom/milo/pull/2748

Resolves: [MWPW-156749](https://jira.corp.adobe.com/browse/MWPW-156749)

**Test URLs:**

Onhover play
- Before: https://main--milo--mokimo.hlx.live/drafts/ruchika/videoplay-onhover?martech=off
- After: https://marquee-cls--milo--mokimo.hlx.live/drafts/ruchika/videoplay-onhover?martech=off

### CODE REVIEW

**Comment by mokimo** [comment]
Seems like PSI is having a bad day. Can be ignored.

**Review by overmyheadandbody — APPROVED** [review]
I noticed something interesting on the Bacom page that might deserve another look, although as part of another story, since this is the current behavior on production today as well.

I captured a couple of frames and noticed that:
* initially the text is on the right side, the left side is empty;
* the text then gets pushed to the left (CLS?);
* background gets applied;
* CTAs slightly shrink, leading to a bit more content jump (CLS?).

Here's a stop motion animation of what's going on on the left side, that's what I wanted to focus on:

https://github.com/user-attachments/assets/54d7ed79-e41d-4058-8d43-66fec4eab5e1

**Comment by mokimo** [comment]
@overmyheadandbody did you encounter this on the branch? That's the CLS that should have gotten fixed with this

**Comment by mokimo** [comment]
@SilviuLCF can you see if you can reproduce what @overmyheadandbody saw? 🤔

**Comment by overmyheadandbody** [comment]
@mokimo - only on Bacom do I see this behavior, both on the before and the after links. All other are very "stable". It's likely there's some sort of override there that should be analyzed as part of a different story, since I suspect it has nothing to do with the video. CC: @SilviuLCF

**Review by SilviuLCF — APPROVED** [review]
@mokimo @overmyheadandbody 
Cannot reproduce it anymore on after url on bacom. 
I will still keep an eye on it. 
PR is verified and can be merged to STAGE

**Review by robert-bogos — APPROVED** [review]

**Comment by mokimo** [comment]
Moving some of the tests to the description:

Onviewport play
- Before: https://main--milo--mokimo.hlx.live/drafts/siva/products/videoplay-onviewport?martech=off
- After: https://marquee-cls--milo--mokimo.hlx.live/drafts/siva/products/videoplay-onviewport?martech=off

Only desktop (mobile should not load the video for perf reasons)
- Before: https://main--milo--mokimo.hlx.live/drafts/seanchoi/marquee-video?martech=off
- After: https://marquee-cls--milo--mokimo.hlx.live/drafts/seanchoi/marquee-video?martech=off

CLS
- Before: https://main--milo--adobecom.aem.live/drafts/osahin/magento-commerce-1
- After: https://marquee-cls--milo--mokimo.aem.live/drafts/osahin/magento-commerce-1

Bacom tests
- Before: https://stage--bacom--adobecom.hlx.live/products/real-time-customer-data-platform/rtcdp?milolibs=stage
- After: https://stage--bacom--adobecom.hlx.live/products/real-time-customer-data-platform/rtcdp?milolibs=marquee-cls--milo--mokimo

**Pull request merged**
