### PR TITLE
MWPW-146491 Increase Target timeout again and improve error analytics

### PR DESCRIPTION
**Pull request by vgoodric**
The Milo target timeout call was recently increased from 2s to 3.5s and is still timing out too early for some users. When that happens the target test is invalid.

Also, the analytics we added recently suffer from 2 issues:
1. The Target timeout is inaccurately reported right after the timeout versus how long the response took.
2. Errors that are not from a timeout are reported as differently.

Proposed fix:
- Increase the default timeout to 4s
- Improve error reporting

Note: @chrischrischris still has a [ticket](https://jira.corp.adobe.com/browse/MWPW-145975) for creating unit tests for martech.js, but the request is urgent so we can't wait for them to be created.

Resolves: [MWPW-146491](https://jira.corp.adobe.com/browse/MWPW-146491)

Test URLs:

Before: https://main--milo--adobecom.hlx.page/?martech=off
After: https://meptimeoutv2--milo--adobecom.hlx.page/?martech=off

Page with Target on:
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout
https://main--homepage--adobecom.hlx.page/homepage/index-loggedout?milolibs=meptimeoutv2

Note: in Dexter, if a Target response came in quite late, the page would "flicker" but they would still get the updates.  In Milo, MEP can only alter the page before decoration.  And we do not want to wait indefinitely before showing the user the page.  So we opted to pick a timeout and move on without the updates if needed. This resulted in some users being categorized as seeing updates, but viewing an unaltered page.
Some discrepancy is fine, but currently, the discrepancy is so high, that we cannot rely on MEP test results, thus rendering testing in Milo useless.  Since testing yields over 100M/year, we are anxious to resolve the issue as quickly as possible.

### CODE REVIEW

**Review by mokimo — COMMENTED** [review]
Please add a justification on why this is a high priority. If everything is high priority, nothing is - the label is only meant for things that NEED to go into the next merge.

Given that currently only 4 other PRs are ready for stage, it's likely it would go into the next batch anyway https://github.com/adobecom/milo/pulls?q=is%3Aopen+is%3Apr+label%3A%22Ready+for+Stage%22

**Comment by mokimo** [comment]
Also the PR seems to be in draft state, was that a mistake?

**Comment by vgoodric** [comment]
> Please add a justification on why this is a high priority. If everything is high priority, nothing is - the label is only meant for things that NEED to go into the next merge.
> 
> Given that currently only 4 other PRs are ready for stage, it's likely it would go into the next batch anyway https://github.com/adobecom/milo/pulls?q=is%3Aopen+is%3Apr+label%3A%22Ready+for+Stage%22

@mokimo we assumed we would not be in this current batch, but wanted to get into Monday's batch for Tuesday.  Added an explanation to the description for our reasoning for high priority label.

**Comment by vgoodric** [comment]
> Also the PR seems to be in draft state, was that a mistake?

@mokimo no, it was a draft on purpose.  I noticed something was not working the way I wanted, but was too tired to fix it last night.  So converted to draft and fixed this morning.

**Review by chrischrischris — APPROVED** [review]

**Comment by bandana147** [comment]
@vgoodric Could you please add the verified label to facilitate merging?

**Pull request merged**
