### PR TITLE
MWPW-143192: Merch card with 2 CTAs and secure transaction label

### PR DESCRIPTION
**Pull request by Axelcureno**
This PR enables the option of adding 2 CTAs along with the "Secure transaction label" to all Merch card variants and display them properly.

Resolves: [MWPW-143192](https://jira.corp.adobe.com/browse/MWPW-143192)

Tacocat related PR: https://git.corp.adobe.com/wcms/tacocat.js/pull/550

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/axel/bug-fixes/mwpw-143192
- After: https://MWPW-143192--milo--axelcureno.hlx.page/drafts/axel/bug-fixes/mwpw-143192

### CODE REVIEW

**Review by Roycethan — CHANGES_REQUESTED** [review]
@Axelcureno 
1)Can we keep little more padding (may be 16 px) below the secure transaction label ? now its looks more oser to CTA's
image
2)Not sure if its causing due to this change but , plz check the layout issues in the below cards (quantity selector etc..)
image

**Review by Roycethan — CHANGES_REQUESTED** [review]
@Axelcureno 
1) In the after link, the merch card CTA alignment is disturbed in mobile
image

2) In desktop mode the Quantity selector is misaligned:
image

**Comment by Axelcureno** [comment]
> @Axelcureno
> 
> 1. In the after link, the merch card CTA alignment is disturbed in mobile
> 
> image
> 2. In desktop mode the Quantity selector is misaligned:
> 
> image

Mini Compare chart card alignments will be fixed here https://github.com/adobecom/milo/pull/2093 @Roycethan

**Comment by Axelcureno** [comment]
Closing since it's already integrated in milo

**Pull request closed without merging**
