### PR TITLE
fix: update sampleRUM to its latest version

### PR DESCRIPTION
**Pull request by ramboz**
This PR updates the `sampleRUM` instrumentation to the latest version we have.

Mainly adds:
* https://github.com/adobe/helix-rum-js/commit/26d9b2e8afd00458d3b050d3fd152fb55a26adcb
* https://github.com/adobe/helix-rum-js/commit/5295681b6c6f7e5c7f541e058a6bde55892ecc32
* https://github.com/adobe/helix-rum-js/commit/d224c64919b92a0b9915ef9a7ee8205e99704cef
* sanitizes URLs before submitting the data

Addresses part of https://github.com/orgs/adobecom/discussions/1442
Resolves: [MWPW-137805](https://jira.corp.adobe.com/browse/MWPW-137805).
Supersedes: https://github.com/adobecom/milo/pull/1448

### Acrobat

Before: https://main--dc--adobecom.hlx.page/?martech=off
After: https://main--dc--adobecom.hlx.page/?milolibs=update-samplerum--milo--adobecom&martech=off

### BACOM

Before: https://main--bacom--adobecom.hlx.page/?martech=off
After: https://main--bacom--adobecom.hlx.page/?milolibs=update-samplerum--milo--adobecom&martech=off

### CC

Before: https://main--cc--adobecom.hlx.page/?martech=off
After: https://main--cc--adobecom.hlx.page/?milolibs=update-samplerum--milo--adobecom&martech=off

### Milo

Before: https://main--milo--adobecom.hlx.page/?martech=off
After: https://update-samplerum--milo--adobecom.hlx.page/?martech=off

### CODE REVIEW

**Comment by ramboz** [comment]
@auniverseaway I set this as `trivial` since I just copy/pasted over the code we have in the boilerplate. Let me know if you think we need further testing and validation

**Review by mokimo — APPROVED** [review]
Duplicate of https://github.com/adobecom/milo/pull/1448 although this also includes the more recent updates.

If you have any QA person to test & verify this or at least see it doesn't break anything, that would be great - as the code is on prod for every milo consumer.

Here's a PR where we usually sanity-check a few pages for the global navigation that's also used across multiple consumers https://github.com/adobecom/milo/pull/1463

**Review by yesil — APPROVED** [review]

**Comment by ramboz** [comment]
@mokimo Thanks for sharing some test URLs. I checked those manually and didn't see any regressions, and also updated the description with the links I used.

**Comment by ramboz** [comment]
@mokimo @yesil @auniverseaway should I go ahead and merge since this was approved and verified, or are you guys handling this?

**Comment by mokimo** [comment]
@ramboz done! 👍

**Pull request merged**
