### PR TITLE
[Release] Stage to Main 

### PR DESCRIPTION
**Pull request by Ruchika4**
- https://github.com/adobecom/milo/pull/2183

### CODE REVIEW

**Comment by spadmasa** [comment]
Hi @meganthecoder  , Can you please take a look on this and confirm, when verified in stage in CC page we are not able to see the alignment , as how its in Kitchen sync
https://stage--cc--adobecom.hlx.page/drafts/Souj/discover1?milolibs=stage
image

CC : @sigadamvenkata  , @asonnalagi

**Review by sigadamvenkata — APPROVED** [review]

**Review by Roycethan — APPROVED** [review]

**Review by Dli3 — APPROVED** [review]

**Comment by JackySun9** [comment]
Screenshot 2024-04-25 at 9 21 42 AM
Screenshot 2024-04-25 at 9 21 33 AM
I saw a difference from UAR side on main cc live, do you know why?

**Comment by meganthecoder** [comment]
> I saw a difference from UAR side on main cc live, do you know why?
@JackySun9 What's the url?

**Comment by JackySun9** [comment]
https://main--cc--adobecom.hlx.live/creativecloud/plan-recommender/quiz-results?quizkey=cc-quiz&milolibs=stage

**Comment by meganthecoder** [comment]
@JackySun9 I can replicate the issue. Thanks for catching this.

@Ruchika4 It's likely caused by https://github.com/adobecom/milo/pull/2098 so as per the rules, it should be pulled out, right?

**Review by JackySun9 — APPROVED** [review]

**Review by meganthecoder — APPROVED** [review]

**Review by TsayAdobe — APPROVED** [review]

**Pull request merged**
