### PR TITLE
CCD Merch Card Combined changes

### PR DESCRIPTION
**Pull request by Axelcureno**
This PR is a combination of the changes from https://github.com/adobecom/milo/pull/2927, https://github.com/adobecom/milo/pull/2995 and https://github.com/adobecom/milo/pull/3054 to ease the merging backlog caused by the RCP.

Resolves: [MWPW-160518](https://jira.corp.adobe.com/browse/MWPW-160518),  [MWPW-158200](https://jira.corp.adobe.com/browse/MWPW-158200) and [MWPW-158473](https://jira.corp.adobe.com/browse/MWPW-158473)

CCD Gallery: https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?theme=dark

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?martech=off
- After: https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?martech=off

### CODE REVIEW

**Comment by Roycethan** [comment]
@Axelcureno  Plz review below observations: https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?martech=off
1) For no eyebrow case - the title is not in alignment with mnemonic
image
2) In figma the Eyebrow has spec 'detail-s' but in the page its 'detail-m' slot 
    In figma the description has Body S SIze:14pt and See trms link has Body XS Size:12pt
    But on the page - both description and see-terms link are having same Sizes
    In figma  both Description and Pricing have same spec of Body S SIze:14pt but on page they are different

**Comment by Roycethan** [comment]
> @Axelcureno Plz review below observations: https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?martech=off
> 
> 1. For no eyebrow case - the title is not in alignment with mnemonic. - Fixed
> 
> image
> 2. In figma the Eyebrow has spec 'detail-s' but in the page its 'detail-m' slot  - Fixed
>    In figma the description has Body S SIze:14pt and See trms link has Body XS Size:12pt  
>    But on the page - both description and see-terms link are having same Sizes. - Fixed
>    In figma  both Description and Pricing have same spec of Body S SIze:14pt but on page they are different
>    Also h3,h4,p order should be sequential right ? right now from top its h4,h3,p... - By design (No requirements)
> 3. See terms should be underlined by default per figma  - Fixed
> 4. Icon/mnemonic is 40/38 , now its 40/40 -  By design per developer for better adjustment
> 5. Strikethrough pricing style is not rendered. - Fixed
> 
> image
> 6. Color value for Eyebrow Light theme looks same for both Dark and Light scheme. - Not a corerct design/requirement (Dev left comment for Figma)
> 
> * Ideally for Eyebrow dark theme this color seem to be not so visible)
> * Card border is light in figma and on file its dark white
> 
> image
> Expectation: per figma - Light theme: 6D6D6D and Dark theme: F8F8F8 image

Comments on fixes are in line above

**Review by 3ch023 — APPROVED** [review]
looks good atm, but let's point the pr to stage?
and once nico's PR is through we can re-check

**Comment by yesil** [comment]
@Axelcureno can you point your PR to stage?

**Comment by Roycethan** [comment]
@Axelcureno  Pricing and checkout is broken on Safari browser:
https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html?martech=off
image

cc @yesil  @3ch023  @npeltier

**Review by seanchoi-dev — APPROVED** [review]

**Comment by 3ch023** [comment]
I am also checking on https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html and it looks good

**Comment by afmicka** [comment]
@Axelcureno @Roycethan in [figma](https://www.figma.com/proto/7tUtNgFelfMjgPoJ5QcE1k/Merch%40Scale-Frameworks?node-id=2095-22529&t=8hahWyGISCJhs7SZ-1&show-proto-sidebar=1&starting-point-node-id=2034%3A44311), the See terms link is said specifically to be blue (for suggested card at least). The color is changed to grey in this [commit](https://github.com/adobecom/milo/pull/3063/commits/2cf74cb5cc0972c2d04d4df7db5fa7b71c8b7b86). Is there any file/place where this change is documented (need the latest requirements for the automation tests)? cc: @3ch023  
Screenshot 2024-10-25 at 11 26 27

**Comment by afmicka** [comment]
@Axelcureno also, strikethrough price is lighter grey in the card design in figma files. Not sure it that is something that needs to be accommodated as well
Screenshot 2024-10-28 at 10 31 19

**Comment by 3ch023** [comment]
@afmicka would it be ok if we address it in the next PR? this one is blocking another upcoming change that we need soon

**Review by npeltier — APPROVED** [review]

**Comment by Axelcureno** [comment]
> @Axelcureno also, strikethrough price is lighter grey in the card design in figma files. Not sure it that is something that needs to be accommodated as well Screenshot 2024-10-28 at 10 31 19

@afmicka from what browser are you seeing this? It looks as expected in Chrome:
Screenshot 2024-10-28 at 7 45 47 AM

**Comment by afmicka** [comment]
@3ch023 @Axelcureno 
For me the prices are not rendering on CCD page for suggested cards after the latest changes. Could you please take a look? Removing the label until this is comfirmed.

Screenshot 2024-10-28 at 15 45 10

**Comment by afmicka** [comment]
> > @Axelcureno also, strikethrough price is lighter grey in the card design in figma files. Not sure it that is something that needs to be accommodated as well Screenshot 2024-10-28 at 10 31 19
> 
> @afmicka from what browser are you seeing this? It looks as expected in Chrome: Screenshot 2024-10-28 at 7 45 47 AM

@Axelcureno I look at figma files in chrome browser
1. https://www.figma.com/design/7tUtNgFelfMjgPoJ5QcE1k/Merch%40Scale-Frameworks?node-id=2034-44369&node-type=frame&t=5QtthpCU9hdUai35-0

2. https://www.figma.com/proto/7tUtNgFelfMjgPoJ5QcE1k/Merch%40Scale-Frameworks?node-id=2034-44369&t=8hahWyGISCJhs7SZ-1&show-proto-sidebar=1&starting-point-node-id=2034%3A44311

**Comment by Axelcureno** [comment]
> @3ch023 @Axelcureno For me the prices are not rendering on CCD page for suggested cards after the latest changes. Could you please take a look? Removing the label until this is comfirmed.
> 
> Screenshot 2024-10-28 at 15 45 10

@afmicka prices render fine for me. Can you share more details of browser and URL? Are you connected to VPN? Please keep in mind only Chrome browser is in scope for this project. I see fonts are also not rendering in your page, that should not be happening. 

Screenshot 2024-10-28 at 7 49 22 AM

**Comment by afmicka** [comment]
> > @3ch023 @Axelcureno For me the prices are not rendering on CCD page for suggested cards after the latest changes. Could you please take a look? Removing the label until this is comfirmed.
> > Screenshot 2024-10-28 at 15 45 10
> 
> @afmicka prices render fine for me. Can you share more details of browser and URL? Are you connected to VPN? Please keep in mind only Chrome browser is in scope for this project. I see fonts are also not rendering in your page, that should not be happening.
> 
> Screenshot 2024-10-28 at 7 49 22 AM

Sorry, did not finish the message properly before hitting enter.
Safari browser: https://ccd-axel-changes--milo--adobecom.hlx.page/libs/features/mas/docs/ccd.html

**Comment by Roycethan** [comment]
@Axelcureno Looks like you changed the color for Strikethrough to "Blue" - can you plz check ?
image

**Pull request merged**
