### PR TITLE
Marquee design polish and 2 image per-viewport support

### PR DESCRIPTION
**Pull request by ryanmparrish**
* Added final design polish to marquee after review
* Extended background decorator utility to now support 1, 2 and 3 per-viewport image options
* Added complete marquee test coverage 💯%

Follow up to: [MWPW-115134](https://jira.corp.adobe.com/browse/MWPW-115134)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/marquee?martech=off
- After: https://marquee-v2--milo--adobecom.hlx3.page/drafts/rparrish/marquee?martech=off

### CODE REVIEW

**Review by amauch-adobe — CHANGES_REQUESTED** [review]
@ryanmparrish the current changes you have made with the 2/3 per-viewport support and polishes look great.  I did notice one thing though, with the Large Marquee light style (not for sure why it doesn't affect the dark style) the background image doesn't stay behind the header text when viewing on mobile/tablet.  I also tried adding an image, thinking maybe that is why the background moves above the text and it didn't make a difference but actually showed how the image also loses its margin/padding when viewed on mobile/tablets.  So kind of two issues, see my screenshots:

Screen Shot 2022-09-14 at 4 51 46 PM

Screen Shot 2022-09-14 at 4 44 17 PM

Other than those two issues, everything else was good on all browsers, platforms.

**Comment by ryanmparrish** [comment]
@amauch-adobe  - Thanks for the review. It seems weird to me too, but thats actually the intended layout for the 'large' marquee. If you reference the [consonant docs](https://consonant.adobe.com/1975e5ba1/p/6377e5-marquee/b/843099) or the [dexter](https://dexter-author.lab02.corp.adobe.com/content/dexter/consonant/xfunwrap-demos/marquee/standard.html?wcmmode=disabled) version, you can see.

**Comment by amauch-adobe** [comment]
@ryanmparrish oh you are right, gee wiz, sorry for the silly concern then.  It makes sense actually now that I think about it in a different context.  I was taking the QA literally for the specific marquee where it was just a gray background image with a little bit of design pattern, it made it look odd since it was just a semi-plain image.  In a real use case the background image is supposed to be more vivid and would explain why the image begins to be stacked above and the text below, etc.  Thanks for setting me straight on that one.  Everything is good on my standpoint then.

**Review by amauch-adobe — APPROVED** [review]
Approved, see my comments above.

**Review by rgclayton — APPROVED** [review]

**Pull request merged**
