### PR TITLE
MWPW-107820 Consonant Tabs

### PR DESCRIPTION
**Pull request by ryanmparrish**
Added a Consonant `Tabs` block to create a simple tabbed interface
  * Supports the following variants (quite, center, dark)
  * An author can include an optional headline row
  * An author can add optional section-metadata to target tabs styling if needed. 

Resolves: [MWPW-107820](https://jira.corp.adobe.com/browse/MWPW-107820)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rparrish/tabs?martech=off
- After: https://tabs--milo--adobecom.hlx.page/drafts/rparrish/tabs?martech=off

### CODE REVIEW

**Comment by ryanmparrish** [comment]
Checking for missing tab content example here -> https://tabs--milo--adobecom.hlx3.page/drafts/rparrish/tabs-m

**Review by chrischrischris — APPROVED** [review]

**Comment by auniverseaway** [comment]
Uh... what happened to the LH?

**Comment by ryanmparrish** [comment]
@auniverseaway  - Are you referencing the pink error in this [example](https://tabs--milo--adobecom.hlx3.page/drafts/rparrish/tabs-m)? I am checking for missing content and applying a `data-failed="true"` attr to that empty content is all. LH wasn't touched. LMK if you think this is unnecessary, It's a little diff than a typical block load error.

**Review by amauch-adobe — APPROVED** [review]
Approved, and validated against all browsers, and platforms.  Also compared mobile behavior with tabs that are not stacked but a sliding behavior for out-of-bands tabs as per consonant guidelines.  All is good and ready.

**Comment by ryanmparrish** [comment]
@amauch-adobe  Looks like I had a link in the document that was pointing to youtube.com and that in itself loaded a gang of video player files which killed the PSI score. I removed these and am getting a lot better score now. LMK if you think we can improve anywhere. Thanks ya'll

**Pull request merged**
