### PR TITLE
MWPW-147267: Mini Compare Chart Card UX Feedback

### PR DESCRIPTION
**Pull request by mirafedas**
Changes the condition in merch card slots, so that when there is no content for the slot, we do not insert empty <p> tags.

Resolves: [MWPW-147267](https://jira.corp.adobe.com/browse/MWPW-147267)

**Test URLs:**
- Before: https://www.stage.adobe.com/acrobat/features.html 
- After: https://mwpw-147267-space-under-the-price--milo--mirafedas.hlx.page/drafts/mirafedas/mini-compare-charts/3-cards?martech=off

### CODE REVIEW

**Review by yesil — APPROVED** [review]

**Comment by afmicka** [comment]
@mirafedas @yesil I still see the same gap between the price and CTAs as it was before on the 'after' link. 
Screenshot 2024-05-24 at 12 58 52

I have synced with @yesil, might be other slots are also causing the issue? (highlighted offers one?)
image (1)

**Comment by mirafedas** [comment]
@Axelcureno thank you for looking into this.
The pages you compare are not quite right, because my code has not been merged to the stage branch yet, so the page you check does not contain my changes, I mean this one: https://stage--milo--mirafedas.hlx.page/drafts/mirafedas/mini-compare-charts/3-cards?martech=off .

This PR goes in combination with the PR for tacocat:
https://git.corp.adobe.com/wcms/tacocat.js/pull/596/files

Basically what I want to achieve is:
When the merch card variation is `mini-compare-chart`, and there is no content for the slot, we should not append a slot with an empty `<p>` tag inside, because it creates a space. And in the tacocat PR I removed the bottom margin for the price, leaving only 16px top padding in the footer, to make sure the distance between the price and the footer is 16px (as required on the XD).

The CTA alignment on page that contains my changes look good both on desktop and on smaller screens:
https://mwpw-147267-space-under-the-price--milo--mirafedas.hlx.page/drafts/mirafedas/mini-compare-charts/3-cards?martech=off
(I'm sure you know it, but just a reminder that after every screen resize there's a need to reload the page, otherwise alignment gets off).
We can huddle on this if needed, please let me know.

**Comment by Axelcureno** [comment]
There is a use case where one or more cards have a slot and another one doesn't. Have we tested this use case? We need to ensure alignment doesn't break in this scenario

**Comment by mirafedas** [comment]
@Axelcureno I added quantity selector and promo text to one of the cards, alignment works ok:
https://mwpw-147267-space-under-the-price--milo--mirafedas.hlx.page/drafts/mirafedas/mini-compare-charts/3-cards?martech=off

**Comment by Axelcureno** [comment]
> @Axelcureno I added quantity selector and promo text to one of the cards, alignment works ok: https://mwpw-147267-space-under-the-price--milo--mirafedas.hlx.page/drafts/mirafedas/mini-compare-charts/3-cards?martech=off Screenshot 2024-05-31 at 12 54 04 Screenshot 2024-05-31 at 12 54 48

Thank you @mirafedas !! :D

**Review by Axelcureno — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]

**Comment by afmicka** [comment]
Nala failures are not related to the PR changes. Video block tests are failing on all PRs from forks due to additional console error coming from the martech.

**Pull request merged**
