### PR TITLE
MWPW-119010 - Fix card race condition

### PR DESCRIPTION
**Pull request by meganthecoder**
* Fix race condition in Card block

Resolves: [MWPW-119010](https://jira.corp.adobe.com/browse/MWPW-119010)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/methomas/half-height?martech=off
- After: https://methomas-card-race-condition--milo--adobecom.hlx.page/drafts/methomas/half-height?martech=off

### CODE REVIEW

**Review by Brandon32 — APPROVED** [review]

**Review by auniverseaway — APPROVED** [review]

**Comment by auniverseaway** [comment]
@meganthecoder is this really a DNM? Or can we merge it now?

**Comment by meganthecoder** [comment]
@auniverseaway Dennis needs to test before merging

**Comment by Dli3** [comment]
I've verified the cards no longer display out of order. Thanks @meganthecoder!
@auniverseaway  This is ready to be merged. I can't update the labels, so if you could please.

**Comment by auniverseaway** [comment]
@Dli3 @meganthecoder FWIW: the person who verifies the solution should be the one who adds the label.

**Comment by meganthecoder** [comment]
@auniverseaway Sure, it sounds like there's an access issue though. Can you make sure @Dli3 has permission to change labels?

**Pull request merged**
