### PR TITLE
MWPW-146856: Left/right padding missing on segment cards on mobile 

### PR DESCRIPTION
**Pull request by Axelcureno**
Fixes Left/right padding missing on segment cards on mobile viewport.

**Before:**
Screenshot 2024-04-29 at 9 12 30 PM

**After:**
Screenshot 2024-04-29 at 9 12 09 PM
Tacocat PR: https://git.corp.adobe.com/wcms/tacocat.js/pull/584

Resolves: [MWPW-146856](https://jira.corp.adobe.com/browse/MWPW-146856)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-146856--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by Roycethan — CHANGES_REQUESTED** [review]
@Axelcureno  Can this be fixed for ipad-Mini ?
https://mwpw-146856--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
image

**Review by Roycethan — APPROVED** [review]
Issues reported fixed @Axelcureno

**Comment by Roycethan** [comment]
@yesil When you get chance - this is verified and ready for stage, plz review unit test failures and update to stage thanks

**Review by mokimo — APPROVED** [review]

**Comment by Roycethan** [comment]
@3ch023 / @yesil  There's Unit tests failure, plz fix, so that it can be merged to stage thanks

**Comment by Roycethan** [comment]
@Axelcureno Issue is fixed at https://mwpw-146856--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
image
@yesil Plz review , once after your review , will update the PR

**Comment by yesil** [comment]
waiting for final comments at https://git.corp.adobe.com/wcms/tacocat.js/pull/584#pullrequestreview-9434952

**Comment by Axelcureno** [comment]
> waiting for final comments at https://git.corp.adobe.com/wcms/tacocat.js/pull/584#pullrequestreview-9434952

@yesil comments resolved.

**Review by mokimo — APPROVED** [review]

**Review by 3ch023 — APPROVED** [review]

**Pull request merged**
