### PR TITLE
Various catalog fixes + SWC updates

### PR DESCRIPTION
**Pull request by yesil**
This PR addresses several small UI fixes for the upcoming catalog page release.

Includes: 
- https://git.corp.adobe.com/wcms/tacocat.js/pull/591
- https://git.corp.adobe.com/wcms/tacocat.js/pull/605

Required by: https://github.com/adobecom/cc/pull/307

Resolves:
 - [MWPW-147654](https://jira.corp.adobe.com/browse/MWPW-147654)
 - [MWPW-147678](https://jira.corp.adobe.com/browse/MWPW-147678)
 - [MWPW-147695](https://jira.corp.adobe.com/browse/MWPW-147695)
 - [MWPW-147697](https://jira.corp.adobe.com/browse/MWPW-147697) 
 - [MWPW-147762](https://jira.corp.adobe.com/browse/MWPW-147762)
 - [MWPW-147772](https://jira.corp.adobe.com/browse/MWPW-147772)
 - [MWPW-147849](https://jira.corp.adobe.com/browse/MWPW-147849)
 - [MWPW-147850](https://jira.corp.adobe.com/browse/MWPW-147850)
 - [MWPW-147851](https://jira.corp.adobe.com/browse/MWPW-147851)
 - [MWPW-147854](https://jira.corp.adobe.com/browse/MWPW-147854)
 - [MWPW-147716](https://jira.corp.adobe.com/browse/MWPW-147716)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ilyas/merch-card-collection?martech=off
- After: https://product-catalog-fixes--milo--adobecom.hlx.page/drafts/ilyas/merch-card-collection?martech=off

CC Test URL: https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes

**Performance**
hlx.live score ~86pts: https://pagespeed.web.dev/analysis/https-product-catalog-fixes--milo--adobecom-hlx-live-drafts-ilyas-merch-card-collection/9h7jey7q1y?form_factor=mobile

### CODE REVIEW

**Review by npeltier — APPROVED** [review]
lgtm assuming no regression :)

**Review by 3ch023 — CHANGES_REQUESTED** [review]
when the icon is missing the card layout gets broken
image

**Comment by 3ch023** [comment]
also on kitchen sync there is a trouble with the card title
https://product-catalog-fixes--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
image

**Comment by yesil** [comment]
@3ch023 the icon issue is not a product of this PR. the card collection index used in the Milo page is hand crafted and not entirely correct. Any style issue should be reported with examples in kitchen sink or other pages.

**Comment by Roycethan** [comment]
@yesil Tickets attached to this PR are verified, they are fixed. I see a other issue and tracked here https://jira.corp.adobe.com/browse/MWPW-150558 plz let me know whether you are planning to fix it here or in another PR, thanks

**Comment by yesil** [comment]
@3ch023 could you please review again?

**Comment by yesil** [comment]
@Roycethan although the issue must be fixed, it doesn't seem to be super critical.
I propose to address it in an upcoming PR.
I would like content QA tests to start on catalog as soon as possible.

**Comment by afmicka** [comment]
@yesil after latest changes:
1. we lost the fix for [MWPW-147849](https://jira.corp.adobe.com/browse/MWPW-147849). Also the font size increased drastically. Compare the screenshots how it was, and how it is now
was before the latest commits: Screenshot 2024-05-27 at 11 42 55
now: 
Screenshot 2024-05-27 at 11 42 43

2. I am still able to scroll the page in the background (maybe we could sync for this). [MWPW-147716](https://jira.corp.adobe.com/browse/MWPW-147716)

**Review by 3ch023 — APPROVED** [review]

**Comment by afmicka** [comment]
@yesil i am still seeing the [MWPW-147849](https://jira.corp.adobe.com/browse/MWPW-147849) and [MWPW-147716](https://jira.corp.adobe.com/browse/MWPW-147716) not being completely fixed. However, we may consider to followup those in a separate PR(s) and not block this one anymore. The rest (including consumer pages) looks ok. 

@Roycethan could you please also take a look given there are lot of changes in the scope?

**Comment by afmicka** [comment]
> @afmicka could you please add steps to reproduce the scrolling issue?

@mirafedas Open the [test](https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes) page in Safari on a real device (mine is iPhone 14 Pro latest), open the filter window and try to scroll. The page in the background should not scroll. Here is the screen recording for both portrait and landscape. 
https://github.com/adobecom/milo/assets/9551700/5b47591f-923b-4b3e-a28c-316521f5fc85
https://github.com/adobecom/milo/assets/9551700/ca186cc2-9e7b-4a5d-a0af-0ce7e5c91491

**Comment by Roycethan** [comment]
@yesil @mirafedas @Axelcureno @3ch023   Below in scope issues and regressions needs to be fixed for merge:
In Scope at https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes
1) Product title should not be in blue link but should retain original black
image
2)Good amount of spacing should be present between "ios Android Windows"
image

Regression:

1)The CTA alignment is disturbed and overflown in mini compare chart cards for all locales at mobile/tablet/desktop breakpoints
few examples:
https://main--cc--adobecom.hlx.live/creativecloud?milolibs=product-catalog-fixes&martech=off
image
image
https://main--cc--adobecom.hlx.live/pl/creativecloud?milolibs=product-catalog-fixes&martech=off#
image
image

cc @afmicka  @npeltier

**Comment by yesil** [comment]
@Roycethan @afmicka as per the design: https://xd.adobe.com/view/84200b4e-caf9-428f-98cf-7198a236a4bc-d173/screen/9e57473d-b3de-4ad1-8627-ca485d21871c/variables/

the tablet should shown 3 cards in the same row and buttons must be stretched.

Let me know if you disagree.

**Comment by Roycethan** [comment]
@yesil  Thanks for fixing regressions in Mini compare chart card, few issues/regressions in Catalog page mentioning here:
1) CTA misalignment: https://catalog-fixes--cc--adobecom.hlx.live/products/catalog?martech=off&milolibs=product-catalog-fixes#category=pdf-esignatures
image
cc @afmicka

**Comment by afmicka** [comment]
@yesil there is one remaining gap to be fixed. Tablet view with 2 columns. The gap is still smaller with your changes. 
https://main--cc--adobecom.hlx.live/creativecloud?milolibs=product-catalog-fixes&martech=off
Screenshot 2024-05-30 at 12 43 10

xd: https://xd.adobe.com/view/84200b4e-caf9-428f-98cf-7198a236a4bc-d173/screen/7c930c0a-df97-4206-a944-43f1ad98d731/variables/

Could you please also check the font size for the CTAs? It is smaller with your changes (15px) than on prod (17px) but not sure out of XD what value it should really be. 
https://main--cc--adobecom.hlx.live/pl/creativecloud?milolibs=product-catalog-fixes&martech=off#
Screenshot 2024-05-30 at 12 52 49


cc: @Roycethan

**Pull request merged**
