### PR TITLE
Remove undefined on Manual Card if no description MWPW-117924

### PR DESCRIPTION
**Pull request by meganthecoder**
* Fix bug where "undefined" shows up when there's no description
* Also added similar catches for image, title, and links

Resolves: [MWPW-117924](https://jira.corp.adobe.com/browse/MWPW-117924)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off
- After: https://manual-card-undefined--milo--adobecom.hlx.page/drafts/denli/manualconsonantcards?martech=off

### CODE REVIEW

**Review by chrischrischris — APPROVED** [review]

**Review by auniverseaway — DISMISSED** [review]

**Comment by auniverseaway** [comment]
Screen Shot 2022-09-28 at 2 27 38 PM

Looks like there's a broken block.

**Comment by meganthecoder** [comment]
@auniverseaway There's a separate ticket for that but I can add it to this PR if it's a blocker https://jira.corp.adobe.com/browse/MWPW-117969

**Comment by auniverseaway** [comment]
Ideally in this, but I'm good with whatever.

**Review by sanjayms01 — APPROVED** [review]

**Comment by meganthecoder** [comment]
It looks like the broken block issue isn't specifically about Manual Cards. When you add a link to a table cell without any other content, it doesn't get wrapped in a p tag, causing an error in decorateButtons. Since a link-only card isn't a requirement, I'll move forward and address that bug later.

**Pull request merged**
