### PR TITLE
Control search

### PR DESCRIPTION
**Pull request by karri-sek**
Hi,
     Based on this [comment here](https://github.com/adobecom/milo/pull/676/files) , we would like to control the search URL and option of open the results in a new tab from the author. A sample Doc contains the details like below.
  

Screenshot 2023-05-09 at 11 06 31

**Search url** : optional : a url to search the user text entered on the search bar.
**open in New Tab**:  'no' : append the search text entered on the search bar to the **Search url** and open in the current tab. 
**open in New Tab**:  'yes' : append the search text entered on the search bar to the **Search url** and open in new tab. 

**Test URLs:**

- Before:  https://main--milo--adobecom.hlx.page/en/

- After  : https://control-search--milo--karri-sek.hlx.page/en/

Resolves: [ABPDOCS-140](https://jira.corp.adobe.com/browse/ABPDOCS-140)

### CODE REVIEW

**Comment by adeshmukh-1585** [comment]
Since the PR is already merged into Milo main branch we can pull the changes and create on top of it @karri-sek 

@narcis-radu , can we know what changes are being made to search and gnav ?

**Comment by mokimo** [comment]
@adeshmukh-1585 Yeah, some changes like renaming things and a few small fixes are still in this branch/PR: https://github.com/adobecom/milo/pull/705/files

+ some unit tests for the search coming (soon)

**Review by mokimo — COMMENTED** [review]
Some comments and I'd like to understand a bit better where this request is coming from and the requirements

**Review by mokimo — COMMENTED** [review]
Some comments and I'd like to understand a bit better where this request is coming from and the requirements

**Comment by adeshmukh-1585** [comment]
> Some comments and I'd like to understand a bit better where this request is coming from and the requirements

Hi @mokimo , the request is to control the SERP. Currently, it's hardcoded to HelpX SERP page, and Milo as a library should keep it configurable. So we are trying to add SERP as an author configurable field and the capability to support open in a new tab or current tab.

**Pull request closed without merging**
