### PR TITLE
Added space after price recurrence label for display-per-unit prices

### PR DESCRIPTION
**Pull request by st-angelo-adobe**
Resolves: [MWPW-162361](https://jira.corp.adobe.com/browse/MWPW-162361)

**Test URLs:**
- Before: https://stage--milo--adobecom.hlx.live/libs/features/mas/docs/ccd.html
- After: https://mwpw-162361--milo--adobecom.hlx.live/libs/features/mas/docs/ccd.html

### CODE REVIEW

**Review by yesil — APPROVED** [review]

**Review by 3ch023 — COMMENTED** [review]
we might need to:

- point this pr to CCD branch
- check why the issue is only reproducible in CCD build, but not on ccd gallery page (it should be reproducible there)
- check if milo cards will not get 2 spaces with this change

will try to sync with @yesil tomorrow, since i need a bit more background

**Review by 3ch023 — CHANGES_REQUESTED** [review]
Hi @st-angelo-adobe could you please point this PR to 'ccd' branch?

**Comment by 3ch023** [comment]
I was able to test it on Studio gallery (it loads no milo styles so the issue is reproducible there)

Before:  https://mwpw-162607--mas--adobecom.hlx.live/gallery/ccd.html?milolibs=ccd--milo--adobecom
After: https://mwpw-162607--mas--adobecom.hlx.live/gallery/ccd.html?milolibs=mwpw-162361--milo--adobecom

However, this adds an additional space to Milo prices, which already have a space:
Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
After: https://mwpw-162361--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
image

**Comment by st-angelo-adobe** [comment]
@3ch023 Thanks, I fixed it, and changed the target branch.

**Review by 3ch023 — APPROVED** [review]

**Pull request merged**
