### PR TITLE
MWPW-146755: RTL merch icon padding

### PR DESCRIPTION
**Pull request by Axelcureno**
Fixes RTL padding on merch card icons.

Resolves: [MWPW-146755](https://jira.corp.adobe.com/browse/MWPW-146755)

Reported URL: 
Before: https://main--cc--adobecom.hlx.page/eg_ar/products/illustrator/text-to-vector-graphic
After: https://main--cc--adobecom.hlx.page/eg_ar/products/illustrator/text-to-vector-graphic?milolibs=MWPW-146755--milo--adobecom

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-146755--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by overmyheadandbody — APPROVED** [review]
Cards seem to have proper spacing now

**Review by yesil — APPROVED** [review]

**Review by narcis-radu — APPROVED** [review]
Thank you, Axel!

**Review by mokimo — APPROVED** [review]

**Review by Roycethan — APPROVED** [review]

**Comment by drashti1712** [comment]
Hi @Axelcureno 
The `aem-psi-check` is failing for this PR. Could you please look into it?

**Comment by Axelcureno** [comment]
> Hi @Axelcureno The `aem-psi-check` is failing for this PR. Could you please look into it?

@drashti1712  it's now passing. Thank you.

**Pull request merged**
