### PR TITLE
MWPW-141539 update deps

### PR DESCRIPTION
**Pull request by VKniaz**
This PR introduced a fix when the user manually entered the number of licenses and then pressed the mouse outside the quantity selector, the amount applied to the quantity attribute in the button.

Resolves: [mwpw-141539](https://jira.corp.adobe.com/browse/mwpw-141539)

Test URLs:

Before: https://main--milo--adobecom.hlx.page/drafts/vkniaziev/qunatity-select?martech=off
After: https://mwpw-141539--milo--vkniaz.hlx.page/drafts/vkniaziev/qunatity-select?martech=off

### CODE REVIEW

**Review by yesil — COMMENTED** [review]
@VKniaz  can you include the reference to your tacocat PR?
I would like to check whether all these deps need to be updated.
From the description, it looks like you only need to update merch-offer-select.js

**Comment by VKniaz** [comment]
@yesil https://git.corp.adobe.com/wcms/tacocat.js/pull/521/files
changes where in: 
packages/web-components/src/merch-card.js
packages/web-components/src/merch-offer-select.js
packages/web-components/src/merch-quantity-select.js

**Review by yesil — APPROVED** [review]

**Comment by yesil** [comment]
@VKniaz  please work with @reuben to validate.

**Comment by VKniaz** [comment]
@yesil is already in progress, thanks.

**Review by Axelcureno — APPROVED** [review]

**Pull request merged**
