### PR TITLE
MWPW-137335: Upgrade md2docx to v2.1.31

### PR DESCRIPTION
**Pull request by sukamat**
Merges the latest changes from https://github.com/adobe/helix-md2docx (v2.1.31).

Includes the following fixes:
- https://github.com/adobe/helix-md2docx/issues/302
- https://github.com/adobe/helix-md2docx/issues/327

Resolves: [MWPW-137335](https://jira.corp.adobe.com/browse/MWPW-137335)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://md2docx-upgrade--milo--adobecom.hlx.page/?martech=off

### CODE REVIEW

**Review by mokimo — APPROVED** [review]
You still need a label for this PR

**Review by overmyheadandbody — APPROVED** [review]
Conditional approve, pending adding the proper labels.

**Comment by mokimo** [comment]
Also, please DO NOT merge this until after the blackout period

**Comment by sukamat** [comment]
Thanks! Added the label.
Just FYI, this is going to the `loc` branch and not to `main`. So it should not affect the freeze.

**Review by nishantka — APPROVED** [review]

**Comment by sukamat** [comment]
Merging to `loc` branch.

**Pull request merged**
