### PR TITLE
Added download and open-in spectrum icons

### PR DESCRIPTION
**Pull request by draganatrajkovic**
Resolves: [MWPW-147409](https://jira.corp.adobe.com/browse/MWPW-147409)

We would like to use `sp-icon-download` and `sp-icon-open-in` in our project.

LINKS:
Before: https://mwpw-147409-search-initial--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/search
After: https://mwpw-147409-search-initial--dme-partners--adobecom.hlx.page/channelpartners/drafts/dragana/search?milolibs=spectrum-icons-download-open-in--milo--draganatrajkovic

Before: https://main--milo--adobecom.aem.live/
After: https://spectrum-icons-download-open-in--milo--draganatrajkovic.aem.live/

### CODE REVIEW

**Comment by narcis-radu** [comment]
Hey @draganatrajkovic - please link the JIRA ticket and provide before and after URLs for testing.

**Comment by draganatrajkovic** [comment]
> Hey @draganatrajkovic - please link the JIRA ticket and provide before and after URLs for testing.

I updated the comment since I raised pr on our project, thank you @narcis-radu

**Review by mokimo — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]

**Review by mirafedas — APPROVED** [review]

**Comment by mokimo** [comment]
Please ensure to get the checks green, I've added dummy links to get the PSI check running.
Otherwise this needs manual intervention to be either merged or fixed by an admin.

**Comment by mokimo** [comment]
@draganatrajkovic

**Comment by draganatrajkovic** [comment]
@mokimo Thank you for the update. I'll make sure to get the checks green in the future PRs.

**Pull request merged**
