### PR TITLE
[Release] Stage to Main

### PR DESCRIPTION
**Pull request by yesil**
Includes:
 - https://github.com/adobecom/milo/pull/1957
 - https://github.com/adobecom/milo/pull/1946
 - https://github.com/adobecom/milo/pull/2014
 - https://github.com/adobecom/milo/pull/2006
 - https://github.com/adobecom/milo/pull/1901
 - https://github.com/adobecom/milo/pull/2016

### CODE REVIEW

**Review by fullcolorcoder — APPROVED** [review]

**Comment by Roycethan** [comment]
@yesil  I have few issues mentioned in https://jira.corp.adobe.com/browse/MWPW-144575 which needs to be fixed before this goes to Main , hence won't be able to sign off at the moment... discussed with @mirafedas on those

**Review by Roycethan — CHANGES_REQUESTED** [review]
@yesil I have few issues mentioned in https://jira.corp.adobe.com/browse/MWPW-144575 which needs to be fixed before this goes to Main , hence won't be able to sign off at the moment... discussed with @mirafedas on those

**Comment by Ruchika4** [comment]
Our team is still seeing some issue with the modal in iphone with the fix going in this PR. Please see the details in the ticket here https://jira.corp.adobe.com/browse/MWPW-144601

cc @sigadamvenkata  @spadmasa @dstrong23 @salonijain3 @yesil @mirafedas

**Review by JackySun9 — APPROVED** [review]

**Review by JFernandezAdobe — APPROVED** [review]

**Review by Dli3 — APPROVED** [review]

**Comment by spadmasa** [comment]
Validation done from CC and details are updated in https://jira.corp.adobe.com/browse/MWPW-144601

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by Roycethan** [comment]
> @yesil I have few issues mentioned in https://jira.corp.adobe.com/browse/MWPW-144575 which needs to be fixed before this goes to Main , hence won't be able to sign off at the moment... discussed with @mirafedas on those

Fixed with https://github.com/adobecom/milo/pull/2021

**Review by Roycethan — APPROVED** [review]

**Pull request merged**
