### PR TITLE
fix(MWPW-148021):Table min width set to screen size.

### PR DESCRIPTION
**Pull request by sharath-kannan**
* Table min width set to screen size  for screen sizes smaller than 400px.

Resolves: [MWPW-148021](https://jira.corp.adobe.com/browse/MWPW-148021)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/sharathkannan/plans?martech=off
- After: https://mwpw-148021--milo--sharath-kannan.hlx.live/drafts/sharathkannan/plans?martech=off

### CODE REVIEW

**Comment by mokimo** [comment]
How to test this? I don't seem to get any tables on the test page

**Comment by sharath-kannan** [comment]
> How to test this? I don't seem to get any tables on the test page

could you check it now? 
ps:clear cache might be required.

**Review by overmyheadandbody — APPROVED** [review]
Thanks for looking into this, @sharath-kannan! I actually reported this issue on Friday as part of the Consonant block review. Looking at the CSS file, I see the media queries are quite disorganized, I'll make a suggestion to refactor it to have a clear media query strategy in the future.

CC: @Ruchika4

**Review by mokimo — APPROVED** [review]

**Review by mokimo — COMMENTED** [review]
Make sure to assign a QA/QE and have them apply the ready for stage label

**Comment by spadmasa** [comment]
Hi @sharath-kannan  , when verified with the feature branch , still see the table being cut off in the sides.Can you please check 
https://main--cc--adobecom.hlx.page/products/firefly/plans?milolibs=mwpw-148021--milo--sharath-kannan
image
https://mwpw-148021--milo--sharath-kannan.hlx.page/docs/library/blocks/table
image

**Comment by Anupamasonnalagi** [comment]
Verified the issue.
https://main--cc--adobecom.hlx.page/products/firefly/plans?milolibs=mwpw-148021--milo--sharath-kannan
image
IMG_3839
IMG_3838
IMG_3837
IMG_3836

**Pull request merged**
