### PR TITLE
Add support for npm start

### PR DESCRIPTION
**Pull request by hparra**
Test:

- https://mwpw-devex-1--milo--hparra.hlx.page/

### CODE REVIEW

**Comment by hparra** [comment]
We have some flakey tests on stage. I had to rerun this.

**Review by overmyheadandbody — COMMENTED** [review]
I don't think it hurts to have this, but at the same time it's quicker to write `aem up` than `npm run start`. With `npm run libs` I get it, one needs to remember how to define a port and which port to use. Also, all Milo projects specify running `aem up` in their README and I'd probably stick to that to avoid any confusion. It can also be that a new developer uses `npm run start` here and will expect the same to work on CC, which doesn't have this enabled, also potentially causing confusion.

If others see value in having this command, then we can probably have it, but we need to ensure all Milo projects are updated so we keep things consistent.

As some final nits - even if trivial, it's useful to have a story for any PR so we can check context in the future. We don't usually implement things unless they're needed and we define those needs in stories. Lastly, just as an FYI, the `zero-impact` label is applied automatically based on certain criteria, I'm wondering whether we should add this file to the exceptions, wdyt @mokimo?

**Comment by mokimo** [comment]
@overmyheadandbody yeah, we should definitely add it

**Review by mokimo — COMMENTED** [review]
I personally mapped it in my zshconfig and boot milo using https & tls certificates. That way I can just run `milo-s` in the terminal from anywhere and any location.
`alias milo-s="cd ~/repos/milo && aem up --tls-cert ~/repos/milo/.hlx/server.crt --tls-key ~/repos/milo/.hlx/server.key --port 3000"`

I agree with @overmyheadandbody that there should be some knowledge about what aem & the aem-cli is and how it works, so that developers know what they use across projects.

**Comment by hparra** [comment]
Start is special, like test: npm start. Historically, start and test are always defined in node projects. See https://docs.npmjs.com/cli/v6/commands/npm-start

Feel free to close.

**Comment by mokimo** [comment]
> Start is special, like test: npm start. Historically, start and test are always defined in node projects. See https://docs.npmjs.com/cli/v6/commands/npm-start

Yup, I agree @overmyheadandbody in the terms of consistency 'works milo, doesn't work on milo-cc', we'd need to update it for consumers and the boilerplate... hence I'll close this

**Pull request closed without merging**
