### PR TITLE
MWPW-140280 | Enhancement to sticky bottom functionality in Milo.

### PR DESCRIPTION
**Pull request by aishwaryamathuria**
As a part of Milo sticky functionality enhancement for 'promobar' block [MWPW-133055](https://jira.corp.adobe.com/browse/MWPW-133055) we had received a request to have a certain scroll behaviour for sticky-bottom functionality when used with promobar block.
The block, when used with sticky-bottom, was supposed to show after we scroll past a section and hide at the footer.
We have received a new request for promobar now [MWPW-140280](https://jira.corp.adobe.com/browse/MWPW-140280) where the new behaviour will be required but only if the author requests it with a section style. By default it would behave like Milo sticky component (always visible and sits above footer).
The PR makes the following changes -
1. Remove different behaviour of sticky-bottom with promobar. sticky-bottom with promobar will have default milo behaviour.
2. Add additional style to section 'sticky-bottom-hide' which will borrow functionality from sticky-bottom and also make the block visible after user scrolls past a section above the section with 'sticky-bottom-hide' section metadata.
3. As per the expected promobar behaviour, the block would hide as soon as the footer comes into focus if authored with 'sticky-bottom-hide'
4. If the 'sticky-bottom-hide' section has a 'no-delay' configured the block will be visible at page load and user does not need to scroll past a section to make the sticky block visible.

Resolves: [MWPW-140280](https://jira.corp.adobe.com/browse/MWPW-140280)

**Test URLs:**
- Before: https://main--milo--aishwaryamathuria.hlx.page/drafts/mathuria/promobar/creativecloud?martech=off
- After: https://mwpw-140280--milo--aishwaryamathuria.hlx.page/drafts/mathuria/promobar/creativecloud?martech=off

https://mwpw-140280--milo--aishwaryamathuria.hlx.page/drafts/mathuria/promobar/creativecloud-default?martech=off

### CODE REVIEW

**Comment by rgclayton** [comment]
What's going on with performance scores? They are showing pretty low.

**Comment by aishwaryamathuria** [comment]
> What's going on with performance scores? They are showing pretty low.

@rgclayton Not sure why the check showed a low score.. I re-ran a couple times and now the check is passing.

**Review by Sartxi — APPROVED** [review]

**Review by amitbikram — APPROVED** [review]

**Comment by Anupamasonnalagi** [comment]
Test details have been added in: https://jira.corp.adobe.com/browse/MWPW-140821

**Comment by aishwaryamathuria** [comment]
The requirement will be re-evaluated to check if other existing features can be leveraged here. Hence closing this ticket and PR.

**Pull request closed without merging**
