### PR TITLE
MWPW-130730 - Geo modal CTA highlight inconsistency

### PR DESCRIPTION
**Pull request by suhjainadobe**
Geo pop up highlight for the CTA is not consistent

Resolves: [MWPW-130730](https://jira.corp.adobe.com/browse/MWPW-130730)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/suhjain/toc
- After: https://modal-tab--milo--suhjainadobe.hlx.page/drafts/suhjain/toc

### CODE REVIEW

**Comment by suhjainadobe** [comment]
@rgclayton @auniverseaway : Please review again here. Closed the previous PR.(https://github.com/adobecom/milo/pull/1412)
@Ruchika4 : The issue has been resolved for all the modals.

**Comment by suhjainadobe** [comment]
My understanding from Victor's comment was that we have to resolve the accessibility issue for Milo in general. Thus implemented the styles on button.  If that is not required then I can make it specific to modals only. 
@ryanmparrish @Ruchika4 @rgclayton @vhargrave

**Comment by vhargrave** [comment]
> My understanding from Victor's comment was that we have to resolve the accessibility issue for Milo in general. Thus implemented the styles on button. If that is not required then I can make it specific to modals only. @ryanmparrish @Ruchika4 @rgclayton @vhargrave

Thanks for tagging me @suhjainadobe. I'll quickly weigh in. If a user is tabbing on a normal CTA button, I believe the tabbing experience should be consistent for them on Adobe.com. This means I think the consonant team should be contacted, asked how the tabbed outline should look for our blue CTA buttons and go with what they expect. I don't see the urgency or need to start changing the tabbed outline for individual buttons, and that's what my comment on the Jira ticket was for. Let's just get this right everywhere. Anyway, I think you've got two options right now. 
1. Pause this PR, contact the consonant folks and ask what outline the blue CTA buttons should have when tabbed on
2. Just make a change for the georouting.

**Comment by suhjainadobe** [comment]
> > My understanding from Victor's comment was that we have to resolve the accessibility issue for Milo in general. Thus implemented the styles on button. If that is not required then I can make it specific to modals only. @ryanmparrish @Ruchika4 @rgclayton @vhargrave
> 
> Thanks for tagging me @suhjainadobe. I'll quickly weigh in. If a user is tabbing on a normal blue button, I believe the tabbing experience should be consistent for them on Adobe.com. This means I think the consonant team should be contacted, asked how the tabbed outline should look for our blue CTA buttons and go with what they expect. I don't see the urgency or need to start changing the tabbed outline for individual buttons, and that's what my comment on the Jira ticket was for. Let's just get this right everywhere. Anyway, I think you've got two options right now.
> 
> 1. Pause this PR, contact the consonant folks and ask what outline the blue CTA buttons should have when tabbed on
> 2. Just make a change for the georouting.

Then maybe we can raise it only for georouting and not for the milo buttons in general. Ill make the changes if everyone aligns with it. 
@rgclayton @vhargrave @chrischrischris @auniverseaway @salonijain3

**Review by vhargrave — APPROVED** [review]
Button outline is now blue on mobile 👍 
When testing on mobile the outline for the tabbed text is yellow though. It's not a part of your task, but maybe we want to change that outline color too. 
Screenshot 2023-10-31 at 08 45 16
Screenshot 2023-10-31 at 08 45 24

**Review by auniverseaway — APPROVED** [review]

**Comment by suhjainadobe** [comment]
> When testing on mobile the outline for the tabbed text is yellow though. It's not a part of your task, but maybe we want to change that outline color too.

Sure @vhargrave , ill look into it in a separate ticket.

**Pull request merged**
