### PR TITLE
MWPW-141780 - Clean up Accordion block attributes

### PR DESCRIPTION
**Pull request by elan-tbx**
* This is a small PR intended to clean up the a11y attributes on the Accordion block. The body of each accordion item had a `role="region"` attribute that was redundant, as we only ever have one element used as the body of the accordion item.

Resolves: [MWPW-141780](https://jira.corp.adobe.com/browse/MWPW-141780)

**Test URLs:**

Milo:
- Before: https://main--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off
- After: https://ebartholomew-mwpw-141780-accordion-attr--milo--adobecom.hlx.page/docs/library/blocks/accordion?martech=off

CC:
- Before: https://main--cc--adobecom.hlx.page/drafts/jbrown/batch-02/products/aftereffects?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/jbrown/batch-02/products/aftereffects?martech=off&milolibs=ebartholomew-mwpw-141780-accordion-attr

### CODE REVIEW

**Review by mokimo — APPROVED** [review]
zero impact is for code **not** touching production.

This might still cause a CSO by breaking any automated monitors that could be checking for this attribute or have some sort of DOM snapshots. Unlikely, but definitely possible - PR is good otherwise, but I've removed the label 😁

**Comment by elan-tbx** [comment]
> zero impact is for code **not** touching production.
> 
> This might still cause a CSO by breaking any automated monitors that could be checking for this attribute or have some sort of DOM snapshots. Unlikely, but definitely possible - PR is good otherwise, but I've removed the label 😁

Makes sense! No worries

**Review by SilviuLCF — APPROVED** [review]
Verified 
Testing details https://jira.corp.adobe.com/browse/MWPW-141780

**Comment by mokimo** [comment]
As per the stage automation process: Skipping 2276: MWPW-141780 - Clean up Accordion block attributes due to failing checks
Please resolve the failing check in order to get your PR merged. Only fully green PRs are merged from now on.

**Comment by mokimo** [comment]
Merging this as the failing nala tests are already existing on stage

**Pull request merged**
