### PR TITLE
MWPW-161804: Merch card style auditing

### PR DESCRIPTION
**Pull request by Axelcureno**
Adds specificity to merch card styles to avoid styling conflicts.

Resolves: [MWPW-161804](https://jira.corp.adobe.com/browse/MWPW-161804)

**Test URLs:**
- Before: https://main--mas--adobecom.hlx.live/studio.html?milolibs=ccd--milo--adobecom#path=ccd
- After: https://main--mas--adobecom.hlx.live/studio.html?milolibs=mwpw-161804--milo--adobecom#path=ccd

### CODE REVIEW

**Comment by 3ch023** [comment]
suggestion for 'After' link:
https://mwpw-161804--milo--adobecom.hlx.live/libs/features/mas/docs/ccd.html
or
https://main--mas--adobecom.hlx.live/gallery/ccd.html?milolibs=mwpw-161804--milo--adobecom

**Review by 3ch023 — APPROVED** [review]

**Review by npeltier — APPROVED** [review]
lgtm

**Review by yesil — APPROVED** [review]
LGTM

**Comment by Roycethan** [comment]
@Axelcureno CCD gallry has this style div[slot='image']  which need update i guess ?

**Pull request merged**
