### PR TITLE
 MWPW-104749 - Consonant Media & Z-Pattern Blocks

### PR DESCRIPTION
**Pull request by ryanmparrish**
- Added support for Consonant 'Z Pattern' and 'Media' blocks. 
- Added a foundational decorate utility script. 

Resolves: [MWPW-104749](https://jira.corp.adobe.com/browse/MWPW-104749), [MWPW-105636](https://jira.corp.adobe.com/browse/MWPW-105636) 

**Test URLs:**
- [Z-Pattern Before](https://main--milo--adobecom.hlx.page/drafts/rparrish/z-pattern), [Media Before](https://main--milo--adobecom.hlx.page/drafts/rparrish/media)
- [Z-Pattern After](https://media--milo--adobecom.hlx.page/drafts/rparrish/z-pattern), [Media After](https://media--milo--adobecom.hlx.page/drafts/rparrish/media)

### CODE REVIEW

**Review by auniverseaway — APPROVED** [review]

**Comment by ryanmparrish** [comment]
Just a heads up. I closed the other PR that looked like this and split out some of the concerns ( :icon: support and analytics) so they are easier to digest and test in a follow up PR.

**Review by rgclayton — APPROVED** [review]

**Comment by auniverseaway** [comment]
@ryanmparrish Can you add these blocks to the list of supported blocks in utils.js? After that, we're shipping.

**Comment by ryanmparrish** [comment]
You betcha. added

**Comment by auniverseaway** [comment]
Wonder why the TBT keeps being so inconsistent.

**Pull request merged**
