### PR TITLE
[MWPW-154662] [Accessibility] Visual list is not marked up as list: section

### PR DESCRIPTION
**Pull request by rohitsahu**
make mini-compare footer rows unordered list for accessibility. Removed unordered list default margin.
Testing notes: Please validate on RTL and footer with empty rows as well.

Resolves: [MWPW-154662](https://jira.corp.adobe.com/browse/MWPW-154662)

**Test URLs:**
- Before: https://milo.adobe.com/drafts/rosahu/rosahu/min-compare
- After: https://mwpw-154662--milo--rohitsahu.hlx.page/drafts/rosahu/rosahu/min-compare-tabs?martech=off

### CODE REVIEW

**Review by npeltier — APPROVED** [review]

**Review by mirafedas — APPROVED** [review]

**Comment by rohitsahu** [comment]
@Roycethan  Please validate the PR

**Comment by Roycethan** [comment]
@rohitsahu  
There was change some time back to make action-menu (...) accessible on catalog which is not working in your branch:
https://main--cc--adobecom.hlx.live/products/catalog?milolibs=mwpw-154662--milo--rohitsahu

Expectation:
https://main--cc--adobecom.hlx.live/products/catalog
image

**Comment by rohitsahu** [comment]
@Roycethan I have merged the latest changes in my branch now. Please verify.

**Comment by Roycethan** [comment]
> https://main--cc--adobecom.hlx.live/products/catalog?milolibs=mwpw-154662--milo--rohitsahu

Fixed now , thanks

**Pull request merged**
