### PR TITLE
[Release] Stage to Main

### PR DESCRIPTION
**Pull request by Blainegunn**
_-REMOVED https://github.com/adobecom/milo/pull/1501 with https://github.com/adobecom/milo/pull/2232 due to [MWPW-147495](https://jira.corp.adobe.com/browse/MWPW-147495)_
- https://github.com/adobecom/milo/pull/2191
- https://github.com/adobecom/milo/pull/2201
- https://github.com/adobecom/milo/pull/2210
- https://github.com/adobecom/milo/pull/2213
- https://github.com/adobecom/milo/pull/2214

### CODE REVIEW

**Review by hparra — APPROVED** [review]

**Review by JackySun9 — APPROVED** [review]

**Review by tedAir — APPROVED** [review]

**Review by mokimo — CHANGES_REQUESTED** [review]
This will break the homepage layout

**Review by 3ch023 — CHANGES_REQUESTED** [review]
rejecting, since it might be breaking the homepage.
https://www.stage.adobe.com/uk/?mep=off

from a quick look, this style seems to be missing 
`grid-template-columns: repeat(12, 1fr);`
image

**Comment by 3ch023** [comment]
UPD. issue is most likely caused by  https://github.com/adobecom/milo/pull/1501 
https://github.com/adobecom/milo/pull/2228/files#diff-7d6d5811a084df948c503699455ce384eb2f73adec6f11a4ad201c74c4ecf16dR172

**Review by mokimo — APPROVED** [review]
Stage looks good again. @Roycethan can you re-test? I've removed the HP SOT label, as we had an issue there.

**Review by overmyheadandbody — APPROVED** [review]

**Review by Dli3 — APPROVED** [review]

**Pull request merged**
