### PR TITLE
Modal meta

### PR DESCRIPTION
**Pull request by Axelcureno**
- Adds support for customizing modal metadata.
- Option to display no curtain/backdrop.
- Option to set modal positioning (bottom left).
- Option to display modal without URL hashing.
- Option to trigger modal from custom event listener.

Resolves: [MWPW-120020](https://jira.corp.adobe.com/browse/MWPW-120020)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://modal-meta--milo--adobecom.hlx.page/?martech=off

### CODE REVIEW

**Comment by vhargrave** [comment]
Just two things for the PR description:
* I want to know what Jira Task this relates to , to compare the acceptance criteria with what this code is actually doing. Because the Jira Task is not linked though, it's a little hard for me to know if this was implemented correctly :D 
* Secondly, the after link should be https://modal-meta--milo--adobecom.hlx.page . For some reason this is returning a 404 though. We probably want to get this fixed before thinking about merging.

**Comment by vhargrave** [comment]
You can see the build pipeline is failing because a label is missing from the PR. It needs to be either 'verified-fixed' or 'trivial'. I don't fully understand these labels yet either, but I'd add 'trivial' as a label to your PR :) .

**Comment by vhargrave** [comment]
Oops - I've just realized that your PR is a draft! 
Sorry for that. Ignore all my feedback :D

**Review by vhargrave — CHANGES_REQUESTED** [review]
Hey Axel
Is this your first Milo PR? If so graz man! 
Can you change your PR description with before and after links so that a reviewer can test this quickly? 
So create a file in the milo project where you'd open a modal but without a curtain for example, and link those files in the before & after URL

**Comment by auniverseaway** [comment]
I'm closing this for now. @Axelcureno has moved on to commerce, and I wrote the bulk of this and I'm pretty sure I want to change some parts of it. @Blainegunn ping me for when you need this and we'll get this shipped.

**Pull request closed without merging**
