### PR TITLE
MWPW-135830 - Decorate Area for fragments

### PR DESCRIPTION
**Pull request by seanchoi-dev**
- This will enable consumer to alter fragment's html before decorate it.

Resolve: [MWPW-138901](https://jira.corp.adobe.com/browse/MWPW-138901)

Usage:
- Add your decorateArea function to milo CONFIG.

Example: https://github.com/adobecom/milo-college/blob/main/scripts/scripts.js

### CODE REVIEW

**Comment by skumar09** [comment]
@seanchoi-dev : I am observing Nala Merch Cards test scripts are failing on your branches. Can you please verify (please have latest code base on your pr branche )

**Review by auniverseaway — COMMENTED** [review]
Test?

Seems like you could do something fairly simple by providing a mock config object into fragments.test.js.

**Comment by seanchoi-dev** [comment]
I added a simple test for decorateArea()

**Comment by honstar** [comment]
@seanchoi-dev : quick question regarding the example in `milo-college`: afaiu, every image within a fragment would be eagerly loaded, no? Wouldn't this be a problem in case multiple fragments with images are used?

**Review by auniverseaway — APPROVED** [review]

**Review by rgclayton — APPROVED** [review]

**Review by sukamat — APPROVED** [review]

**Pull request merged**
