### PR TITLE
[MWPW-156187][Milo Catalog Accessibility] "more actions" on catalog cards not accessible

### PR DESCRIPTION
**Pull request by seanchoi-dev**
Resolves: [MWPW-156187](https://jira.corp.adobe.com/browse/MWPW-156187)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://merch-card-accessibility--milo--adobecom.hlx.page/?martech=off

**Test for consumer site:**
- Before: https://main--cc--adobecom.hlx.page/products/catalog
- After: https://main--cc--adobecom.hlx.page/products/catalog?milolibs=merch-card-accessibility

### CODE REVIEW

**Review by Axelcureno — APPROVED** [review]

**Review by 3ch023 — APPROVED** [review]

**Review by Roycethan — CHANGES_REQUESTED** [review]
@seanchoi-dev @Axelcureno 
aria-label="Action menu" and tabindex="0" added for action-menu
Now with tabbing , screen reader can access action-menu

Observed one regression where when user clicks action menu and move away the cursor , the action menu is still visible - In production upon click and move away, we are hiding the action-menu.
Have attached video showing first production(expected) behavior   and current branch behavior.
[

https://github.com/user-attachments/assets/34d7ab86-f444-4b7e-8443-cb73b1cb724b

](url)

**Review by Roycethan — CHANGES_REQUESTED** [review]
@seanchoi-dev Reviwed, the focus issue on click is fixed, however now the Screen reader only reads action menu as "Clickable" and doesn't say or read "Clickable Action-menu", not sure why to remove area-label or probably it needs a name/label/alt ?

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev Reviwed, the focus issue on click is fixed, however now the Screen reader only reads action menu as "Clickable" and doesn't say or read "Clickable Action-menu", not sure why to remove area-label or probably it needs a name/label/alt ?

I removed the aria-label because Nala test failed for having it on the div: "Violation: Ensure ARIA attributes are not prohibited for an element's role"

**Comment by Roycethan** [comment]
> * https://main--cc--adobecom.hlx.page/products/catalog?milolibs=merch-card-accessibility

@seanchoi-dev so the accessible name to have is an requirement for screen reader. for other alternatives they have given few recommendations in this ticket https://jira.corp.adobe.com/browse/DOTCOM-129835 - plz review thanks

**Comment by seanchoi-dev** [comment]
> > * https://main--cc--adobecom.hlx.page/products/catalog?milolibs=merch-card-accessibility
> 
> @seanchoi-dev so the accessible name to have is an requirement for screen reader. for other alternatives they have given few recommendations in this ticket https://jira.corp.adobe.com/browse/DOTCOM-129835 - plz review thanks
> 
> `WCAG Success Criteria: 4.1.2 Name, Role, Value (Level A)
> 
> Code Snippet:
> 
> Remediation Recommendation: To fix this issue, BOTH a ROLE and a NAME must be provided for the button.
> 
> Provide a ROLE by using one of the following techniques:
> 
> 1. Use a native HTML  element.
> 
> Apply now!
> 
> 2. Add role="button" to the custom button container. NOTE: If you use role="button" instead of , you will need to ensure Enter and Spacebar can activate the button.
> 
> Provide a NAME by using any of the following techniques:
> 
> 1. Use the innertext of the  or role="button" element
> 
> Apply now!
> 
> Apply now!
> 
> 2. Use a non-empty aria-label attribute on the  or role="button" element.
> 
> `

I added text w/ font-size=0 and role="button".  I also tested with voice over, it seems good to me.

**Comment by Roycethan** [comment]
> * https://main--cc--adobecom.hlx.page/products/catalog?milolibs=merch-card-accessibility

Thanks , That works !

**Review by Roycethan — APPROVED** [review]

**Pull request merged**
