### PR TITLE
MWPW-133181 marquee rtl issue.

### PR DESCRIPTION
**Pull request by sharath-kannan**
* Marquee in rtl alignment has been fixed.

Resolves: [MWPW-133181](https://jira.corp.adobe.com/browse/MWPW-133181)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/eg_ar/drafts/tat28144/blocks/marqueeblock?martech=off
- After: https://mwpw-133181--milo--sharath-kannan.hlx.page/eg_ar/drafts/tat28144/blocks/marqueeblock?martech=off

### CODE REVIEW

**Comment by sharath-kannan** [comment]
@ryanmparrish , @auniverseaway can you kindly check and approve the PR?

**Comment by bandana147** [comment]
You can add a param ?martech=off to your test urls, so that your Lighthouse check doesn't fail

**Review by chrischrischris — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]
I'm seeing some unexpected spacing for the links section, due to an empty link added as the first element:
Screenshot 2023-07-28 at 11 02 04

This pushes out the rest of the CTAs and is happening on both RTL and LTR directions. Is this coming from faulty authoring or is it a bug that needs some attention?

**Review by ryanmparrish — APPROVED** [review]
Take a quick look at the spacing comment from @overmyheadandbody, otherwise looks good.

**Pull request merged**
