### PR TITLE
MWPW-120935 - [SEO Structured Data] Event

### PR DESCRIPTION
**Pull request by jckautzmann**
- add SEO data when the page is set as Event in the metadata

Resolves: [MWPW-120935](https://jira.corp.adobe.com/browse/MWPW-120935)

Notes:
- mixed event is not supported (`"eventAttendanceMode": "https://schema.org/MixedEventAttendanceMode”,`)
- authoring (Word/gdoc): meta data key is written with ‘-‘  so that it’s easier to read in HTML:
    - Word/gdoc: `Offers-Price-Currency | USD`
    - HTML: `<meta name="offers-price-currency" content="USD”>`

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/jck/test-seo-event?martech=off
- After: https://seo-event--milo--adobecom.hlx.page/drafts/jck/test-seo-event?martech=off

Content model:

Screenshot 2023-01-09 at 17 59 23

JSON-LD in the rendered HTML:

Screenshot 2023-01-09 at 18 00 48

### CODE REVIEW

**Review by auniverseaway — CHANGES_REQUESTED** [review]
Blocking this until I can look at this more. Something seems off about polluting metadata so much with this content. I'd like to get some author perspectives on this proposed solution.

**Review by vhargrave — CHANGES_REQUESTED** [review]
Fyi, saw the unit tests are failing

**Comment by auniverseaway** [comment]
@jckautzmann I'm finally getting around to this. The more I think about this, the more I think this should be a regular block.

Reason: this is a lot for a person to type out. We can leverage the block library so authors don't have to type all this out. If we leave it as metadata, it wouldn't be library-able. Thoughts?

cc @rgclayton

**Comment by jckautzmann** [comment]
> this should be a regular block
@auniverseaway Agreed. I'll rework the PR once I'm done with the breadcrumbs enhancements.

**Review by fullcolorcoder — CHANGES_REQUESTED** [review]
I see some more changes are coming, changing review status for now.

**Comment by rgclayton** [comment]
> @jckautzmann I'm finally getting around to this. The more I think about this, the more I think this should be a regular block. 
Reason: this is a lot for a person to type out. We can leverage the block library so authors don't have to type all this out. If we leave it as metadata, it wouldn't be library-able. Thoughts?

I think this is a great idea. This sounds like a good pattern for any structured data that requires more than a few properties to update.

**Comment by chrischrischris** [comment]
Closing PR while @jckautzmann reworks it to be a block.

**Pull request closed without merging**
