### PR TITLE
MWPW-114236 - [SEO Structured Data] Article

### PR DESCRIPTION
**Pull request by jckautzmann**
- add SEO data when the page is set as News Article in the metadata
- gnav.js: remove nested blocks

Resolves: [MWPW-114236](https://jira.corp.adobe.com/browse/MWPW-114236)

Pending:
- support for data validation in the Sidekick

Currently not supported:
- defining several images
- defining several authors

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/jck/test3?martech=off
- After: https://seo-article--milo--adobecom.hlx.page/drafts/jck/test3?martech=off

Content model:

| Metadata                                                                   |           |
--- | ---
| richresultstype  | NewsArticle                                                        |
| image                     | https://example.com/photos/1x1/photo.jpg     |
| title                         | Title of a News Article                                       |
| published              | 2015-02-05 |
| modified                | 2016-02-05 |
| authorname                    | Author1                                           |
| authorurl                    | https://example.com/author1                                           |

HTML:
```
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "headline": "Title of a News Article",
      "image": "https://example.com/photos/1x1/photo.jpg",
      "datePublished": "2015-02-05",
      "dateModified": "2016-02-05",
      "author": {
          "@type": "Person",
          "name": "Author1",
          "url": "https://example.com/author1",
        }
    }

```

### CODE REVIEW

**Comment by fullcolorcoder** [comment]
@jckautzmann can we see a sample page of this in action? There is no json present on the after link.

**Comment by kptdobe** [comment]
For the dates, if the author has to provide the values, you probably want to have a more simple format, like `2016-02-05 09:20`.

**Comment by jckautzmann** [comment]
@fullcolorcoder You can have see the generated SEO data for the page at https://main--milo--adobecom.hlx.page/drafts/jck/test1

**Comment by jckautzmann** [comment]
@kptdobe About the date format: 
- the expected date format in the SEO generated data is [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601), e.g.: 2022-11-08
- we could have a date picker for the author. @auniverseaway Is there a date picker in Milo?
- otherwise we expect the author to enter an ISO-8601 formatted date

**Comment by fullcolorcoder** [comment]
> @fullcolorcoder You can have see the generated SEO data for the page at https://main--milo--adobecom.hlx.page/drafts/jck/test1

I only see <meta> values for NewsArticle, no JSON. Is this on purpose?

**Comment by jckautzmann** [comment]
@fullcolorcoder sorry, wrong branch. Please check this link:
https://seo-article--milo--adobecom.hlx.page/drafts/jck/test1
The data looks as follows in the <head> tag:
Screenshot 2022-11-08 at 18 08 03

**Review by fullcolorcoder — APPROVED** [review]
@jckautzmann nice, looking good to me. I validated the JSON and tested this out on another page for pagespeed performance in a more real world scenario. https://pagespeed.web.dev/report?url=https%3A%2F%2Fseo-article--milo--adobecom.hlx.page%2Fdrafts%2Fbradjohn%2Fprincess-cruises-case-study-html%3Fmartech%3Doff gets 100 on LH. I think the YT videos and missing block on the test URL are causing lower scores for https://seo-article--milo--adobecom.hlx.page/drafts/jck/test1

**Comment by jckautzmann** [comment]
@fullcolorcoder Thx for your review! After discussing with @vhargrave I made some updates to the PR, to improve naming and support for author name and url at https://github.com/adobecom/milo/pull/290/commits/54aafe38d4c19e91c1bdb0466db0f044ccdf6e35.
Could you please validate the changes?

**Comment by auniverseaway** [comment]
@jckautzmann this is mostly great! Thanks for this.

It raises some interesting questions about how we should solve these schemas when they are page-based, and not triggered by a block (i.e. breadcrumbs).

Something we try to do is minimize how non-critical code lives directly in `utils.js`. In this, I would do something similar to how we did favicon or even interlinks. You could do something like:

```js
if (isDoc) {
  if (getMetadata('richresults')) import('../features/richresults.js');
  loadFooter();
}
```
This would keep the bulk of your code out of utils and it would gate the over-the-wire impact for pages that don't have any richresults needs. I like this because it means we have one (ish) source of truth for how we tackle rich results.

In the example above, this assumes you have a self invoking function that would be called. You may need to tweak my suggestion if you get cycle dependency errors and need to pass in some functions out of utils. If so, you can see our sidekick js import for prior art.

**Review by auniverseaway — CHANGES_REQUESTED** [review]
Mostly great. Some small suggestions above. I would also change the name of `richresultstype` to just `richresults` as "type" is inferred.

Coming from AEM, you may appreciate this: https://experiencemanaged.com/posts/improve-the-aem-authoring-experience-ax

**Comment by jckautzmann** [comment]
@auniverseaway Thx for reviewing this PR! I addressed your feedback at https://github.com/adobecom/milo/pull/290/commits/828acd190736d4d5a3848da807227afcf89adb72 and added a few tests.

**Review by vhargrave — APPROVED** [review]
looks very good now

**Review by auniverseaway — APPROVED** [review]

**Pull request merged**
