### PR TITLE
[MWPW-157451] [Accessibility] Merch cards | Focus is lost on comparing plans section

### PR DESCRIPTION
**Pull request by rohitsahu**
remove tabindex=0 as the attributes from merch-card div

Resolves: [MWPW-157451](https://jira.corp.adobe.com/browse/MWPW-157451)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/rosahu/rosahu/min-compare-tabs  
- After: https://mwpw-157451--milo--rohitsahu.hlx.live/drafts/rosahu/rosahu/min-compare-tabs

### CODE REVIEW

**Review by mirafedas — APPROVED** [review]

**Comment by mirafedas** [comment]
@rohitsahu try adding marquee on your test page to make the PSI check green

**Review by Axelcureno — APPROVED** [review]

**Comment by rohitsahu** [comment]
@Roycethan Please validate this as well

**Comment by rohitsahu** [comment]
@rahulgupta999 what is the bug?

**Comment by Roycethan** [comment]
> @Roycethan Please validate this as well

@rohitsahu  Validated, plz resolve the conflicts on the below files - will push it tomorrow
libs/deps/mas/mas.js
libs/features/mas/mas/dist/mas.js

**Comment by rohitsahu** [comment]
@Roycethan resolved

**Pull request merged**
