### PR TITLE
MWPW-159157: Update modal to account for new image size

### PR DESCRIPTION
**Pull request by mirafedas**
We added support for a new class in the media block: 'space-between', which when added will add additional space between the right and left parts of the media block, see [Figma](https://www.figma.com/proto/Bvg6OTmb7WnzN8RcA3VrSC/Q4-24-BF%2FCM-All-Apps-Promo?page-id=0%3A1&node-id=10010-40784&viewport=3084%2C3842%2C0.07&t=emC0Wy3D2f49ELvt-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=1%3A2&disable-default-keyboard-nav=1).

Updated authoring documentation: https://main--milo--mirafedas.hlx.page/docs/authoring/promotions/delayed-modal

Resolves: [MWPW-159157](https://jira.corp.adobe.com/browse/MWPW-159157)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.page/products/aftereffects/free-trial-download?instant=2024-11-15T14:00:00.000Z 
- After: https://mwpw-159157-media-space-between--milo--mirafedas.hlx.page/drafts/mirafedas/delayed-modals/delayed-modal-space-between?georouting=off&martech=off

### CODE REVIEW

**Review by Blainegunn — APPROVED** [review]
makes sense

**Comment by skumar09** [comment]
@mirafedas: Nala video tests are failing on your PR branch. Can you please verify
- Your branch failing test URL: https://mwpw-159157-media-space-between--milo--mirafedas.hlx.live/drafts/nala/blocks/video/youtube-video
- main branch video test URL: https://main--milo--adobecom.hlx.live/drafts/nala/blocks/video/youtube-video

I guess your branch requires the latest video block changes.

cc: @narcis-radu @mokimo @robert-bogos

**Review by Axelcureno — APPROVED** [review]

**Review by Roycethan — CHANGES_REQUESTED** [review]
@mirafedas Theres this error logged and breaking commerce on Mac-Safari:
Can you plz check ?
image
https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mwpw-159157-media-space-between--milo--mirafedas

cc @npeltier  @afmicka

**Comment by Roycethan** [comment]
> @mirafedas Theres this error logged and breaking commerce on Mac-Safari: Can you plz check ? image https://main--cc--adobecom.hlx.live/creativecloud?milolibs=mwpw-159157-media-space-between--milo--mirafedas
> 
> cc @npeltier @afmicka

Fixed with Revert PR: https://github.com/adobecom/milo/pull/2987

**Review by Roycethan — APPROVED** [review]

**Pull request merged**
