### PR TITLE
MWPW-147299 How-to MP4 Videos

### PR DESCRIPTION
**Pull request by Blainegunn**
The "How-to" block will now support inline MP4 videos.

Resolves: [MWPW-147299](https://jira.corp.adobe.com/browse/MWPW-147299)
**NALA PR** - https://github.com/adobecom/nala/pull/368

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/gunn/how-to-vid?martech=off
- After: https://mwpw-147299--milo--adobecom.hlx.page/drafts/gunn/how-to-vid?martech=off

### CODE REVIEW

**Comment by colloyd** [comment]
@Blainegunn Looks like the last two examples in your "after" page have some sort of vertical alignment issues? The first two look good, though.

**Review by fullcolorcoder — APPROVED** [review]

**Comment by narcis-radu** [comment]
I checked small screens (~800px) and the video is too small to be usable. Are there any recommendations for small screens / tablets? Maybe we want to flow into a mobile view.
Screenshot 2024-06-04 at 10 47 57

**Review by overmyheadandbody — COMMENTED** [review]
Code looks good, but I do agree with @narcis-radu that breakpoints deserve a closer look.

From a naming perspective, I see the wrapper is still called `how-to-image`, when in fact it contains a video. Could it be updated to `how-to-media` or something more relevant to the multiple use-cases?

**Comment by Blainegunn** [comment]
@narcis-radu PdM and design have already signed off. I happy to go back with your concerns but their primary objective is getting this live as is. 
@overmyheadandbody that's a fair point, I've made the update

**Review by colloyd — APPROVED** [review]

**Review by narcis-radu — CHANGES_REQUESTED** [review]
@Blainegunn - I will take your suggestion to confirm with design on this particular use-case. My concern is that the video is not really viewable on lower viewport sizes unless we make it fullscreen (which is hard to do since you cannot reach the controls).

**Comment by Blainegunn** [comment]
@narcis-radu fixed breakpoint for video. It will now only appear to the right of the content on desktop. On tablet and mobile it will go below.

**Review by narcis-radu — APPROVED** [review]

**Comment by Blainegunn** [comment]
NALA Test will pass after this merge 
QA Authority @skumar09 asked me to merge this one first.

**Comment by mokimo** [comment]
@robert-bogos as the MPOC will need to manually merge this once the linting errors in the nala tests have been fixed

**Pull request merged**
