### PR TITLE
MWPW-147245 Quiz entry block Tests

### PR DESCRIPTION
**Pull request by fullcolorcoder**
Adds tests for quiz-entry 
Resolves: [MWPW-147245](https://jira.corp.adobe.com/browse/MWPW-147245)

Tests aren't 100% coverage yet, this gets us started and surfaces refactoring needed.

**Test URLs:**
- Before: https://quiz-entry-block--milo--adobecom.hlx.page/drafts/colloyd/quiz-entry/?martech=off
- After: https://quiz-entry-block--milo--fullcolorcoder.hlx.page/drafts/colloyd/quiz-entry/?martech=off

### CODE REVIEW

**Review by colloyd — APPROVED** [review]

**Comment by JackySun9** [comment]
could you fix the eslint

**Comment by colloyd** [comment]
> could you fix the eslint

Still seeing one linting issue regarding single quote strings

**Comment by colloyd** [comment]
> > could you fix the eslint
> 
> Still seeing one linting issue regarding single quote strings

NM, looks like you got it.

**Comment by JackySun9** [comment]
This one is not working now https://quiz-entry-block--milo--fullcolorcoder.hlx.page/drafts/colloyd/quiz-entry/?debug=quiz-entry

@fullcolorcoder @colloyd

**Review by JackySun9 — APPROVED** [review]

**Pull request merged**
