### PR TITLE
[MWPW-146756] Add support for RTL in aside notifications, horizontal cards

### PR DESCRIPTION
**Pull request by narcis-radu**
Add RTL support for some notifications and horizontal cards on mobile and desktop.

Resolves: [MWPW-146756](https://jira.corp.adobe.com/browse/MWPW-146756)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/eg_ar/drafts/narcis/page?martech=off
- After: https://mwpw-146756--milo--narcis-radu.hlx.page/eg_ar/drafts/narcis/page?martech=off

**Horizontal cards**
- After: https://main--cc--adobecom.hlx.page/eg_ar/cc-shared/fragments/products/illustrator/what-can-you-create-in-illustrator?martech=off&milolibs=mwpw-146756--milo--narcis-radu

**Notifications**
- After: https://main--cc--adobecom.hlx.page/eg_ar/products/illustrator/pricing-info?martech=off&milolibs=mwpw-146756--milo--narcis-radu

### CODE REVIEW

**Review by robert-bogos — APPROVED** [review]

**Review by SilviuLCF — APPROVED** [review]
Verified , ready for stage 

Testing details 
https://jira.corp.adobe.com/browse/MWPW-146756

**Review by overmyheadandbody — APPROVED** [review]
RTL changes look good; unrelated to this PR, I think selectors such as `[dir = "rtl"] .three-up .card-horizontal.tile .foreground .card-block .card-image img` could be difficult to maintain and affect CSS performance, we might want to look into making these more efficient in the future

**Review by Sartxi — APPROVED** [review]
LGTM, but why are the lighthouse scores low? May need to add a marquee to the document to make those pass

**Comment by narcis-radu** [comment]
As @Sartxi pointed out - the low LH scores are due to missing content, not code changes. The same low scores are visible on the main branch where the code changes are not available yet https://pagespeed.web.dev/analysis/https-main--milo--adobecom-hlx-page-eg_ar-drafts-narcis-page/9vz4ig5erp?form_factor=mobile.

**Pull request merged**
