### PR TITLE
fix(MWPW-133207):Intermittent screen freeze, backdrop does not close when modal is closed.

### PR DESCRIPTION
**Pull request by sharath-kannan**
This is the second PR for the screen freeze issue.
Intermittently seeing the issue of screen getting frozen when the geo routing popup is closed.
The root cause of this issue is because of the condition in the close function in which the backdrop is always assumed to be the next element of the modal in dom, which is not always the case,I have noticed few I-frames and script tags are getting added in between them and this happens only windows systems intermittently.

The issue has been resolved by removing the first backdrop that comes after the modal in the dom.
Resolves: [MWPW-133207](https://jira.corp.adobe.com/browse/MWPW-133207)

Test URLs:

Before: https://main--milo--adobecom.hlx.page/drafts/Anupama/aside-block-with-play-on-hover-z-pattern?georouting=on&martech=off
After: https://mwpw-133207--milo--sharath-kannan.hlx.page/drafts/Anupama/aside-block-with-play-on-hover-z-pattern?georouting=on&martech=off

### CODE REVIEW

**Comment by rgclayton** [comment]
@sharath-kannan How is this marked as verified without any reviews?

**Comment by skumar09** [comment]
@sharath-kannan : NalaText block automation scripts are failing on your branch,  due to the latest changes to text block from [Milo PR -1370](https://github.com/adobecom/milo/pull/1370), please update your branch to the latest milo code-base.
cc : @rgclayton

**Comment by sharath-kannan** [comment]
> @sharath-kannan How is this marked as verified without any reviews?

@rgclayton This has been verified by @Dli3 in bacom and @JFernandezAdobe in dc.
kindly refer to the comments in this [ticket](https://jira.corp.adobe.com/browse/MWPW-133207).

**Comment by sharath-kannan** [comment]
> @sharath-kannan : NalaText block automation scripts are failing on your branch, due to the latest changes to text block from [Milo PR -1370](https://github.com/adobecom/milo/pull/1370), please update your branch to the latest milo code-base. cc : @rgclayton

@skumar09 Updated the branch.

**Review by meganthecoder — APPROVED** [review]

**Comment by asonnalagi** [comment]
**Verified the issue for the dc, cc and bacom teams, its working fine now.**

https://main--bacom--adobecom.hlx.page/products/analytics/marketing-attribution?milolibs=MWPW-133207--milo--sharath-kannan
https://stage--dc--adobecom.hlx.live/acrobat/online/convert-pdf?milolibs=MWPW-133207--milo--sharath-kannan
https://main--cc--adobecom.hlx.page/drafts/tat28144/genericvideobtn/demovideomodal?milolibs=MWPW-133207--milo--sharath-kannan
https://mwpw-133207--milo--sharath-kannan.hlx.page/drafts/Anupama/aside-block-with-play-on-hover-z-pattern?georouting=on&martech=off
https://main--cc--adobecom.hlx.page/creativecloud/animation/discover?milolibs=MWPW-133207--milo--sharath-kannan
https://www.adobe.com/?milolibs=MWPW-133207--milo--sharath-kannan
Screenshot (27026)
image
image

**Review by Brandon32 — APPROVED** [review]

**Pull request merged**
