### PR TITLE
MWPW-121560 Correct alignment of Review component on desktop viewport

### PR DESCRIPTION
**Pull request by nkthakur48**
Aligns review component to center of container on desktop viewport

Screenshot 2022-11-22 at 9 55 02 PM

Resolves: [MWPW-121560](https://jira.corp.adobe.com/browse/MWPW-121560)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/?martech=off
- After: https://mwpw-121560-review-center--milo--nkthakur48.hlx.page/

### CODE REVIEW

**Review by So1ene — APPROVED** [review]

**Comment by ryanmparrish** [comment]
I know this isn't related to the alignment fix, but is this form input styled correctly? Looks good otherwise. 
Screen Shot 2022-11-22 at 9 44 09 AM

**Comment by nkthakur48** [comment]
Hi @ryanmparrish, please note that styles for review component has been picked AS IS from it's counterpart in dexter's codebase.

Screenshot 2022-11-22 at 10 29 30 PM
URL - https://dexter-author.dev05.corp.adobe.com/content/dexter/us/en/raga/samplenewpagetest.html?wcmmode=disabled

Nevertheless, I agree that styles could be re-looked again by XD folks and we could implement any suggestions :)

**Review by Axelcureno — APPROVED** [review]
This change looks good to me but will defer to @auniverseaway on whether this should be a global block change. I think it should.

**Review by auniverseaway — APPROVED** [review]

**Comment by auniverseaway** [comment]
@ryanmparrish @nkthakur48 I created a follow up ticket: https://jira.corp.adobe.com/browse/MWPW-121593

Thanks for fixing this!

**Pull request merged**
