### PR TITLE
[MWPW-105625] - Consonant Text block

### PR DESCRIPTION
**Pull request by elan-tbx**
Adds basic Text block. Allows for full-width, 2-column, and 3-column variants.
Resolves: [MWPW-105625](https://jira.corp.adobe.com/browse/MWPW-105625)

Test URLs:

- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/text
- After: https://text-block--milo--adobecom.hlx.page/drafts/ebartholomew/text

### CODE REVIEW

**Review by amauch-adobe — CHANGES_REQUESTED** [review]
@elan-tbx was there any unit tests created for the text block?  All blocks should have unit tests created under the tests directory.

**Comment by elan-tbx** [comment]
> @elan-tbx was there any unit tests created for the text block? All blocks should have unit tests created under the tests directory.

@amauch-adobe shoot, sorry, another thing that got lost in the consonant migration. I have added the tests, updated them to match the latest convention, and pushed up the changes.

**Review by amauch-adobe — CHANGES_REQUESTED** [review]
Thanks for adding the tests @elan-tbx , I did find an issue with styling when I added three CTA links/buttons.  See my screenshots below, it looks like when you add a third CTA button (similar to what you would find on marquees) the two buttons scrunch up to each other or the other way around with the text link scrunching up with the button.  According to the acceptance criteria in the ticket, it states it should support double actions and a text link, which would entail two buttons and a text link.  Was that requirement changed and no longer valid?

Screen Shot 2022-09-12 at 2 55 15 PM

Screen Shot 2022-09-12 at 2 55 22 PM

**Comment by amauch-adobe** [comment]
Everything else looked good.  I tested it out on all platforms and browsers, accessibility testing was good too.

**Comment by elan-tbx** [comment]
@amauch-adobe Good point, I had been going off the XD file (which only shows a max of two CTAs), but that does make it sound like 3 should be supported. I've added a style tweak to work with this, does that look okay to you?

**Comment by amauch-adobe** [comment]
@elan-tbx you know what let's not do the three CTA's option.  You were right from the start, I just looked back at the consonant library that you linked in the ticket (my apologies for not doing this at the start).  We should be "on brand" rather than clutter up the text block since they should use a different type of block if they are wanting that ability as stated in the consonant page for the text block.  So full disclosure let's remove the third CTA and keep to what we had originally.

**Comment by amauch-adobe** [comment]
@elan-tbx once you make that revert of styling this will be approved.

**Review by amauch-adobe — APPROVED** [review]

**Comment by elan-tbx** [comment]
@amauch-adobe sounds good, thanks! I've reverted that styling so it should be ready to go

**Review by amauch-adobe — COMMENTED** [review]
Reviewed the latest changes for the addition of the tests, already approved prior.

**Review by auniverseaway — APPROVED** [review]

**Pull request merged**
