### PR TITLE
MWPW-136885: Merch Card Accessibility

### PR DESCRIPTION
**Pull request by Axelcureno**
- Introduces keyboard navigation for better accessibility inside merch cards.
- Navigates from LTR with Tab key and RTL with Shift + Tab.
- Navigates between merch cards and all links inside them.

Note: This PR is only the consumption of changes from https://git.corp.adobe.com/wcms/tacocat.js/pull/553

Resolves: [MWPW-136885](https://jira.corp.adobe.com/browse/MWPW-136885)

**Test URLs:**
- Before: https://main--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-136885--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by Roycethan — CHANGES_REQUESTED** [review]
@Axelcureno  
The tab order here https://mwpw-136885--milo--axelcureno.hlx.page/docs/library/kitchen-sink/merch-card?martech=off looks ok now 
But When looking at https://main--cc--adobecom.hlx.page/products/catalog?milolibs=mwpw-136885--milo--axelcureno
image

1) I see the tab order withing card collection is not proper.. digging more see that "IndexInParent" for first card is "25" which is not correct , it should be "1"

**Review by yesil — CHANGES_REQUESTED** [review]
tabbing should be trapped inside a card.
after the last element, it should not do anything.
Currently it jumps to the next focusable DOM element but visually it is not the right element since grid items are ordered with the css `order` style.
Arrow keys properly navigates to next/previous cards.
I suggest tab should do nothing after the last focusable element in a card.

**Comment by Axelcureno** [comment]
> tabbing should be trapped inside a card. after the last element, it should not do anything. Currently it jumps to the next focusable DOM element but visually it is not the right element since grid items are ordered with the css `order` style. Arrow keys properly navigates to next/previous cards. I suggest tab should do nothing after the last focusable element in a card.

I totally agree with that approach to be more consistent with the UX. I've implemented it. Please check @yesil 

cc @Roycethan

**Review by yesil — APPROVED** [review]

**Review by honstar — APPROVED** [review]

**Review by 3ch023 — APPROVED** [review]

**Review by Roycethan — APPROVED** [review]
Validated, one of discrepancy found on tab order of cards is tracked here https://jira.corp.adobe.com/browse/MWPW-146141
so this ticket implemented merch card tabbing and arrow key focus.
approving the PR [Axel Cureno Basurto](https://jira.corp.adobe.com/secure/ViewProfile.jspa?name=axel) to move forward

**Comment by afmicka** [comment]
@Axelcureno please resolve conflicts on this branch. cc: @Roycethan

**Pull request merged**
