### PR TITLE
MWPW-128867: fixes number of Results per page being ignored

### PR DESCRIPTION
**Pull request by cmiqueo**
Removes unused option "None" from the Pagination Type dropdown

"None" is set as the default option in the configurator Pagination Type dropdown, which is making the CaaS react code to ignore the number set for "Results Per Page"

This change aligns the behavior with the AEM implementation of the Consonant Card Collection

Resolves: [MWPW-128867](https://jira.corp.adobe.com/browse/MWPW-128867)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/tools/caas?martech=off (displays 10 cards)
- After: https://MWPW-128867--milo--adobecom.hlx.page/tools/caas?martech=off (displays 5 cards)

### CODE REVIEW

**Review by JasonHowellSlavin — APPROVED** [review]

**Comment by Ruchika4** [comment]
@cmiqueo , how do we see the remaining 5 cards on the page? Don't see an option to go to next page.
Screen Shot 2023-04-04 at 2 50 24 PM

**Comment by cmiqueo** [comment]
@Ruchika4 To see more cards from the collection you can either:
 - Increase the number of "Results Per Page" in the _Basic_ panel, or 
 - "Enable Pagination" in the _Pagination_ panel

**Review by meganthecoder — APPROVED** [review]

**Review by chrischrischris — APPROVED** [review]

**Review by chrischrischris — CHANGES_REQUESTED** [review]
Also need to update
milo/test/blocks/caas/mocks/utils.js
  45,3:   paginationType: 'none',
milo/tools/caas-import/parseCaasConfig.js
  36,3:   paginationType: 'none',

**Comment by cmiqueo** [comment]
> Also need to update milo/test/blocks/caas/mocks/utils.js 45,3: paginationType: 'none', milo/tools/caas-import/parseCaasConfig.js 36,3: paginationType: 'none',

@chrischrischris  Done!

**Review by sukamat — APPROVED** [review]

**Review by sanrai — APPROVED** [review]

**Pull request merged**
