### PR TITLE
[MWPW-132443] Gnav updates for Blog migration

### PR DESCRIPTION
**Pull request by overmyheadandbody**
I would usually open this PR from my fork, but I got 404s when trying to use the https://branch--repo--owner.hlx.page approach. This branch will be deleted as soon as it is merged.

---

This aims to handle any gaps noticed while testing the FEDS Gnav on Blog. It:
- ensures the region picker dropdown is closed on outside click;
- adds a `No Logo` option to the 'Gnav Brand' and 'Adobe Logo' features. These blocks can now be authored to be just image, just text or both of them together;
- ensures that placeholders used in the global navigation documents are replaced. This was already in place for dropdown menus and the footer;
- provides an additional fallback (`imsClientId`) for the navigation experience name if one hasn't been explicitly defined.

There are still a few things required for a successful migration:
- a few authoring changes. These can be implemented right now and they have no side-effects when still using the Milo Gnav; details will be provided in [MWPW-132443](https://jira.corp.adobe.com/browse/MWPW-132443);
- implementation of contextual search. We're currently doing a due diligence for this feature.

Resolves: [MWPW-132443](https://jira.corp.adobe.com/browse/MWPW-132443)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ramuntea/blog-old-gnav?martech=off
- After: https://gnav-blog-migration-updates--milo--adobecom.hlx.page/drafts/ramuntea/blog-new-gnav?martech=off

### CODE REVIEW

**Review by mokimo — APPROVED** [review]

**Review by narcis-radu — APPROVED** [review]

**Comment by rgclayton** [comment]
Hey @overmyheadandbody would this url be a better after/testing example?
https://main--blog--adobecom.hlx.page/?milolibs=gnav-blog-migration-updates

This tests directly against what we have in the migrated blog. 

For the "region nav" the blog uses the `inline` variant to achieve the mini popup layout for the languages.

**Comment by overmyheadandbody** [comment]
Hey @rgclayton! Yup, `milolibs` can be used as well, I just wanted to showcase the changes in a more 'controlled' environment. The link to test these changes with the Global Navigation code would be: https://main--blog--adobecom.hlx.page/?milolibs=gnav-blog-migration-updates&headerqa=global-navigation&footerqa=global-footer

However, we still need to make the two authoring suggestions from [JIRA](https://jira.corp.adobe.com/browse/MWPW-132443?focusedCommentId=36907295&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36907295). Those shouldn't affect current layout.

Regarding the contextual search, we'll be treating it as a separate story, we have a few ideas on how to optimise the workflow.

**Comment by overmyheadandbody** [comment]
I will soon be merging this if there are no other concerns.

**Comment by honstar** [comment]
@overmyheadandbody , the codecov check currently fails. Do you mind having a look what code should be covered in addition? Thx

**Comment by rgclayton** [comment]
@overmyheadandbody Sorry for the delay in response!

I didn't see a note about the langnav (Change Region) being addressed in that ticket or this PR. Is that something we need a seperate ticket for?

image

**Comment by overmyheadandbody** [comment]
Hey @rgclayton! In the body of the PR I mentioned
> ensures the region picker dropdown is closed on outside click;

Are you looking for other features surrounding the region picker?

We already support the dropdown, I've updated my example page - https://gnav-blog-migration-updates--milo--adobecom.hlx.page/drafts/ramuntea/blog-new-gnav. You can also have a look over the Blogs example page - https://main--blog--adobecom.hlx.page/?milolibs=gnav-blog-migration-updates&headerqa=global-navigation&footerqa=global-footer

**Comment by honstar** [comment]
@overmyheadandbody : looks like there is a merge conflict, can you please check? Thx

**Comment by overmyheadandbody** [comment]
Unit tests passing thanks to https://github.com/adobecom/milo/pull/920, merge conflicts fixed, code coverage improved for Global Navigation (added additional checks in `getUserEntitlements`). However, there is a project-wide coverage drop coming from other areas, Global Navigation is still doing well:

Code coverage for Blog PR

@honstar, do you want to have another look before merging? 😀

**Comment by honstar** [comment]
> @honstar, do you want to have another look before merging? 😀

I think the codecoverage drop came from the personalization PR which introduced some unit test failures that were later fixed by skipping tests. All good from my side 👍

**Review by honstar — APPROVED** [review]

**Pull request merged**
