### PR TITLE
MWPW-151862: Secure transaction label is not center aligned with CTA

### PR DESCRIPTION
**Pull request by mirafedas**
Fixed the secure transaction label vertical alignment on merch cards.

Resolves: [MWPW-151862](https://jira.corp.adobe.com/browse/MWPW-151862)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/docs/library/kitchen-sink/merch-card?martech=off
- After: https://mwpw-151862-secure-transaction-label--milo--mirafedas.hlx.live/docs/library/kitchen-sink/merch-card?martech=off

### CODE REVIEW

**Review by mokimo — APPROVED** [review]

**Review by overmyheadandbody — COMMENTED** [review]
The after link leads to a 404 page, it would be useful to have a working version so reviewers can check the functionality.

**Review by seanchoi-dev — APPROVED** [review]

**Review by yesil — CHANGES_REQUESTED** [review]
@mirafedas I believe you just updated the deps file instead of replacing it.
your tacocat PR is now merged, please build merch-card.js from the develop branch on Tacocat and update here.

**Comment by mirafedas** [comment]
@yesil yes, sorry, now it should be good

**Review by yesil — APPROVED** [review]

**Review by overmyheadandbody — COMMENTED** [review]
There's a conflict needing to be addressed before moving forward with this.

I also see a couple of discrepancies between the before/after links. As an "outsider", it's difficult to judge whether the issue has been fixed, since not all elements relevant to the alignment are present.
| Before | After |
| ------------- | ------------- |
| Screenshot 2024-06-17 at 11 54 18 | Screenshot 2024-06-17 at 11 55 27 |

**Comment by yesil** [comment]
@overmyheadandbody the reason you do not see the CTA on the after URL is CORS, because the feature branch is not allow listed. 

here is before/after
image

image

**Comment by yesil** [comment]
btw this fix has been already merged to stage via another PR, likely: https://github.com/adobecom/milo/pull/2229/files

hence closing, thanks for the review @overmyheadandbody .

**Comment by overmyheadandbody** [comment]
@yesil - I figured CORS is the issue, but I've been thinking more and more that Merch PRs are difficult to test by non-Merch folks. We might need to discuss what we can do to allow anyone to test these.

**Pull request closed without merging**
