### PR TITLE
Column table

### PR DESCRIPTION
**Pull request by seanchoi-dev**
* Enabling `table` option for column block.
* Setting up variables.css to share milo CSS variables with other helix sites.

Resolves: [MWPW-111569](https://jira.corp.adobe.com/browse/MWPW-111569)

**Test URLs:**
- Before: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case
- After: https://column-fix--business-website--adobe.hlx.page/blog/basics/business-case?milolibs=column-table

### CODE REVIEW

**Comment by fullcolorcoder** [comment]
One thing I'm wondering if you should compensate for is lightest/light/dark/darkest theming. Someone could wrap this in section metadata, specify dark for example.

**Review by fullcolorcoder — CHANGES_REQUESTED** [review]
Dark/light theming - I opened a quick PR to update the list of libs. Once approved/merged we should be able to see the section metadata block on biz blog. I tried testing out with section-metadata but realized it wasn't available. 
https://column-fix--business-website--adobe.hlx.page/drafts/bradjohn/5-benefits-having-unified-b2c-and-b2b-ecommerce-site?milolibs=column-table

**Review by amauch-adobe — APPROVED** [review]
Approved, QA validated against all browsers, platforms.

**Review by chrischrischris — APPROVED** [review]

**Review by fullcolorcoder — APPROVED** [review]
We'll have to circle back on the stuff I mentioned I think once we ship those other blocks officially

**Pull request merged**
