### PR TITLE
MWPW-154191: Ability to have green promo text on merch-card to bottom of the card (under description)

### PR DESCRIPTION
**Pull request by mirafedas**
Added a promo-text slot in the listed merch card variants:
- merch-card (product)
- merch-card (mini-compare)
- merch-card (segment)
- merch-card (catalog)
- merch-card (plans)
- merch-card (image)

Resolves: [MWPW-154191](https://jira.corp.adobe.com/browse/MWPW-154191)

**Test URLs:**
Before: 
- Product: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-product?martech=off
- Mini-compare: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-mini-comparison?martech=off
- Segment: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-segment?martech=off
- Catalog: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-catalog?martech=off
- Plans: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-plans?martech=off
- Image: https://main--milo--adobecom.hlx.live/fragments/mirafedas/merch/merch-image?martech=off
After: 
- Product: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-product?martech=off
- Mini-compare: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-mini-comparison?martech=off
- Segment: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-segment?martech=off
- Catalog: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-catalog?martech=off
- Plans: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-plans?martech=off
- Image: https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.live/fragments/mirafedas/merch/merch-image?martech=off

### CODE REVIEW

**Comment by 3ch023** [comment]
Hi @mirafedas , this change is moving the callout text below the description, I am not sure if its expected change?
https://main--milo--adobecom.hlx.page/docs/library/kitchen-sink/merch-card
https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.page/docs/library/kitchen-sink/merch-card
Before
image

After
image

**Review by 3ch023 — CHANGES_REQUESTED** [review]
needs clarification on callout text moving below the description, see
https://mwpw-154191-promo-text-bottom--milo--mirafedas.hlx.page/docs/library/kitchen-sink/merch-card

**Comment by mirafedas** [comment]
@3ch023 I showed the cards to April and she asked to place the callout text under the promo text, see comment in the ticket: https://jira.corp.adobe.com/browse/MWPW-154191 . Should I ask her to double check?

**Review by npeltier — APPROVED** [review]
looks good to me (including call out text placement)

**Review by 3ch023 — APPROVED** [review]

**Comment by yesil** [comment]
@mirafedas there are dependency conflicts.

**Review by Axelcureno — APPROVED** [review]

**Pull request merged**
