### PR TITLE
MWPW-125774 - Quiz block accessibility

### PR DESCRIPTION
**Pull request by colloyd**
* Accessibility adjustments added to quiz option markup
* Quiz options can now be tabbed to with the keyboard
* Quiz options can be activated with space or enter keys
* Focus is reset to the top of the quiz when moving to the next question

Resolves: [MWPW-125774](https://jira.corp.adobe.com/browse/MWPW-125774)

**Test URLs:**
- Before: https://uar-integration--milo--adobecom.hlx.page/drafts/delta/app-recommender-test/?martech=off
- After: https://mwpw-125774-quiz-accessibility--milo--colloyd.hlx.page/drafts/delta/app-recommender-test/?martech=off

### CODE REVIEW

**Comment by echampio-at-adobe** [comment]
Hi @colloyd. I think the code changes generally look good, and the page seems to behave well from an accessibility perspective. I can tab back and forth and activate selections with space and return. 

On mobile, though, when the button layout switches, the buttons should take up the width of the screen, but right now, they're set to the width of the text. 

Screenshot 2023-09-08 at 1 16 51 PM

Also, this example is a contrived one, but when the text becomes verbose, the size of the icon decreases. 

Screenshot 2023-09-08 at 1 21 16 PM

**Comment by colloyd** [comment]
@echampio-at-adobe Adjusted the mobile width to 100% - wasn't necessary before the shift to button elements for the quiz options, but it should look right now.

**Comment by echampio-at-adobe** [comment]
> @echampio-at-adobe Adjusted the mobile width to 100% - wasn't necessary before the shift to button elements for the quiz options, but it should look right now.

Yup. Button width looks good on phone

**Review by overmyheadandbody — COMMENTED** [review]
Please make sure to add the appropriate labels when opening PRs - https://github.com/adobecom/milo/wiki/PR-Labels. Also, the ESLint errors should be addressed, either now or as a later task (since this PR is not yet raised against the `main` branch)

**Review by sabyamon — APPROVED** [review]

**Review by echampio-at-adobe — APPROVED** [review]
I see only one minor ui issue on mobile that can be addressed separately

**Comment by colloyd** [comment]
@echampio-at-adobe I've addressed that mobile issue with icons shrinking as text breaks to more than one line - they should stay the same width regardless of how many lines of text there are.

**Comment by echampio-at-adobe** [comment]
> I see only one minor ui issue on mobile that can be addressed separately

And it's fixed in Cody's latest commit

**Review by fullcolorcoder — APPROVED** [review]

**Pull request merged**
