### PR TITLE
mwpw-153237: Merch @ Scale Test Content

### PR DESCRIPTION
**Pull request by Axelcureno**
Merch at Scale static content to be used for performance checks, etc.
For now only including A.com merch cards. Adobe Home and CCD cards coming soon.
Supports milolibs configuration as URL param.

Jira ticket: https://jira.corp.adobe.com/browse/MWPW-153237

Test URLs:

Before: https://main--milo--adobecom.hlx.live/web-components/test/static/merch-card/index.html
After: https://mwpw-153237--milo--adobecom.hlx.live/web-components/test/static/merch-card/index.html

### CODE REVIEW

**Comment by vhargrave** [comment]
@Axelcureno how could I test this feature to ensure it's looking right?

**Comment by honstar** [comment]
> @Axelcureno how could I test this feature to ensure it's looking right?

I think https://github.com/adobecom/milo/tree/stage/libs/features/mas/web-components/test has some pointers how to test web-components with static content.

**Comment by vhargrave** [comment]
@honstar ah I see this Readme, thanks @honstar ! - https://github.com/adobecom/milo/blob/stage/libs/features/mas/web-components/README.md

**Review by 3ch023 — CHANGES_REQUESTED** [review]
Talked to @yesil a bit about test content, and I think we need to update this PR to reflect the latest stage.

We were not decided if the test pages should be a static HTML or a SharePoint document, I think both are fine, but I see more value in Sharepoint doc.
1. it will make us 1 step more ready to inevitable integration of odin merch cards in Milo
2. we don't need to adjust .hlxignore and spend time there

We could try an autoblock that turns Odin links into this HTML. Similar to how it is implemented with OST.
@yesil already had something drafted for hackathon:
https://mas--cc--adobecom.hlx.live/drafts/ilyas/special-offers?martech=off 

link
https://www.adobe.com/mas/studio.html#path=/content/dam/sandbox/mas/special-offers-students-and-teachers
turn into:
```
<merch-card><merch-datasource path="/content/dam/sandbox/mas/catalog/creative-cloud-all-apps"></merch-datasource></merch-card>
```

**Comment by Axelcureno** [comment]
Closing this PR since the requirement has changed and @3ch023 decided to pick this ticket.

**Pull request closed without merging**
