### PR TITLE
MWPW-140052-Word break css for korean

### PR DESCRIPTION
**Pull request by Ruchika4**
* css to stop korean words breaking into next line
* Also update code to support language based sites for korean word break like blog

Resolves: [MWPW-140052](https://jira.corp.adobe.com/browse/MWPW-140052)

**Test URLs:**
Milo
- Before: https://main--milo--adobecom.hlx.page/kr/drafts/ruchika/document?martech=off
- After: https://kr-word-break--milo--adobecom.hlx.page/kr/drafts/ruchika/document?martech=off

Bacom
- Before: https://main--bacom--adobecom.hlx.page/kr/products/marketo/financial-services?martech=off
- After: https://main--bacom--adobecom.hlx.page/kr/products/marketo/financial-services?milolibs=kr-word-break&martech=off

CC
- Before: https://main--cc--adobecom.hlx.page/kr/creativecloud/tools/app-design-software?martech=off
- After: https://main--cc--adobecom.hlx.page/kr/creativecloud/tools/app-design-software?milolibs=kr-word-break&martech=off

DC
- Before: https://main--dc--adobecom.hlx.page/kr/acrobat/online/compress-pdf?martech=off
- After: https://main--dc--adobecom.hlx.page/kr/acrobat/online/compress-pdf?milolibs=kr-word-break&martech=off

Homepage
- Before: https://main--homepage--adobecom.hlx.page/kr/homepage/index-loggedout?martech=off
- After: https://main--homepage--adobecom.hlx.page/kr/homepage/index-loggedout?milolibs=kr-word-break&martech=off

Bacom-blog
- Before: https://main--bacom-blog--adobecom.hlx.page/kr/blog/?martech=off
- After: https://main--bacom-blog--adobecom.hlx.page/kr/blog/?milolibs=kr-word-break&martech=off

Blog
- Before: https://main--blog--adobecom.hlx.page/ko/?martech=off
- After: https://main--blog--adobecom.hlx.page/ko/?milolibs=kr-word-break&martech=off

### CODE REVIEW

**Review by overmyheadandbody — COMMENTED** [review]
Would this not be needed for Japanese and Chinese as well? Are there different requirements between the 3 locales?

**Comment by Ruchika4** [comment]
> * https://main--bacom--adobecom.hlx.page/kr/products/marketo/financial-services?milolibs=kr-word-break&martech=off

Hi @overmyheadandbody thanks for the review. Japanese did had a different requirement as far as I know and it's been implemented here https://github.com/adobecom/milo/blob/main/libs/features/japanese-word-wrap.js
I am not very sure about Chinese though. However I verified on my local by setting word-break: keep all for Chinese too and didn't work as expected (see the screenshot word is still breaking in different row). So I believe that has to be handled in a separate way too like Japanese. As the ticket raised was for Korean only so this PR is addressing that only for now.

Screen Shot 2023-12-20 at 8 49 54 AM

**Comment by Ruchika4** [comment]
> Would this not be needed for Japanese and Chinese as well? Are there different requirements between the 3 locales?

Hi @overmyheadandbody thanks for the review. Japanese did had a different requirement as far as I know and it's been implemented here https://github.com/adobecom/milo/blob/main/libs/features/japanese-word-wrap.js
I verified on my local by setting word-break: keep all for Chinese too and didn't work as expected (see the screenshot word is still breaking in different row). So I believe that has to be handled in a separate way too like Japanese. As the ticket raised was for Korean only so this PR is addressing that only for now.
Screen Shot 2023-12-20 at 8 49 54 AM

**Comment by Ruchika4** [comment]
@rgclayton as discussed I have updated code to support korean word break for language based sites like Blog. Thanks for pointing that out.

**Review by rgclayton — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]

**Comment by Ruchika4** [comment]
@Dli3 verified and updated the jira ticket. Hence updating the label to verified.

**Comment by Ruchika4** [comment]
Fix has been verified in bacom, homepage, dc, cc, blog. Details in the jira ticket.

**Pull request merged**
