### PR TITLE
MWPW-143145: add instant preview paramter

### PR DESCRIPTION
**Pull request by 3ch023**
Implement the 'instant' parameter for Milo Promotions.
'Instant' param overrides current browser time with provided value and impacts Promo manifests.

### Details
'instant' parameter in the format of ISO 8601 with UTC (GMT) timezone allows GWP to see the page 'in the future' and validate upcoming promotions. It compliments `?mep` parameter (allows to preview manifests on the page) with an ability to validate the configured promo schedule.
[Sample Page](https://instant--milo--3ch023.hlx.live/drafts/mariia/pr/promo/promo?instant=2024-06-14T05:00:00.000Z)

### How to use

1. Open the page with configured promo
2. In MEP Preview click on 'instant'
3. The link with an instant parameter will open in the new tab, you can share the link with anyone for a review

image
image

Resolves: [MWPW-143145](https://jira.corp.adobe.com/browse/MWPW-143145)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/mariia/pr/promo/promo?martech=off
- After: https://instant--milo--adobecom.hlx.live/drafts/mariia/pr/promo/promo?martech=off

### CODE REVIEW

**Comment by vgoodric** [comment]
@3ch023 I don't think I understand the need for this feature. Can't you just choose the experience in the radio list and use that preview link?

**Comment by 3ch023** [comment]
> @3ch023 I don't think I understand the need for this feature. Can't you just choose the experience in the radio list and use that preview link?

Hi, this feature should make validation of promos a bit easier for GWP.

1. it allows checking if no errors were made while configuring the schedule for promos.
e.g. GWP configured accidentally manifest to be active on 1st April instead of 1st March. If you use the current manifest preview - it will work and you won't notice the mistake. Instant parameter pointing at the starting date increases the chances of noticing the mistake.

2. If I am a person validating pages for Black Friday, I don't need to know which manifests exactly are attached to which page. All I need to know is the start date of blackfriday promo and I can copy over the ?instant parameter from Live page to page, validation their promo content. I don't need to switch to Preview/Production (hlx.page/hlx.live) to lookup which manifests should be turned on for this exact page.

**Review by npeltier — APPROVED** [review]
lgtm

**Review by yesil — APPROVED** [review]

**Comment by 3ch023** [comment]
NALA is failing due to unrelated CORS issues on the branch, so marking it ready for stage

**Comment by vgoodric** [comment]
@3ch023 have you merged in my `mepmoreactions` branch?  It should be next to go into stage and you are likely to have conflicts.

**Review by vgoodric — CHANGES_REQUESTED** [review]
adding a request changes until you can confirm you've resolved conflicts with `mepmoreactions` branch

**Review by vgoodric — APPROVED** [review]
Looks like there are no conflicts with stage.  Most of the updates are in the promo-utils so the conflict issues I feared are fine.  Yay.

**Review by chrischrischris — APPROVED** [review]

**Comment by vgoodric** [comment]
@3ch023 Actually I have one small nit.  Can we make the instant link in the MEP button easier to read?  Maybe white but always underlined?
image

**Pull request merged**
