### PR TITLE
Let region nav to use prefix instead content root.

### PR DESCRIPTION
**Pull request by seanchoi-dev**
- Bug fix for region nav when content root is used.

Resolves: [MWPW-131680](https://jira.corp.adobe.com/browse/MWPW-131680)

**Test URLs:**
CC:
- Before: https://main--cc--adobecom.hlx.live/creativecloud/video/hub/ideas/what-is-a-contrast-cut#langnav
- After: https://main--cc--adobecom.hlx.live/creativecloud/video/hub/ideas/what-is-a-contrast-cut?milolibs=region-nav-fix#langnav

DC:
- Before: https://main--dc--adobecom.hlx.live/fr/acrobat/online/word-to-pdf#langnav
- After: https://main--dc--adobecom.hlx.live/fr/acrobat/online/word-to-pdf?milolibs=region-nav-fix#langnav

BACOM (site doesn't have issue now)
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories
- After: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=region-nav-fix

### CODE REVIEW

**Review by Blainegunn — APPROVED** [review]
ty!

**Review by Blainegunn — APPROVED** [review]
ty!

**Review by auniverseaway — APPROVED** [review]

**Review by vhargrave — CHANGES_REQUESTED** [review]
We're still using the contentRoot on line 12 for the fallback route if a route we try navigating to doesn't exist. As said in slack, I don't see how we can cleanly define a fallback route without the contentRoot 🙁

**Comment by seanchoi-dev** [comment]
I discussed with @vhargrave and this is good to merge for now, since it is breaking production for dc and cc, but we definitely want to revisit specially for fallback redirection on handleEvent() since it should redirect the site's root instead adobe.com/{locale prefix}.  We may need something like `config.siteRoot` for this kind of cases.

**Pull request merged**
