### PR TITLE
MWPW-146494-keep gnav sticky when branch banner is displayed

### PR DESCRIPTION
**Pull request by Ruchika4**
* keep gnav sticky when branch banner is displayed

Resolves: [MWPW-146494](https://jira.corp.adobe.com/browse/MWPW-146494)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off
- After: https://stickygnav--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off

CC
- Before: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?martech=off
- After: https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?milolibs=stickygnav&martech=off

### CODE REVIEW

**Review by aishwaryamathuria — APPROVED** [review]

**Comment by spadmasa** [comment]
Verified the below URLS of milo and CC, when the user scrolls the gnav is seen sticky , but when the user opens the menu in gnav and scrolls the content is not seen visible 
https://stickygnav--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off
https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?milolibs=stickygnav&martech=off
image
@Ruchika4  please check on this and confirm.

CC : @sigadamvenkata  , @asonnalagi

**Comment by Ruchika4** [comment]
Hi @spadmasa , I am able to scroll in portrait mode and see all content but see content getting cut in landscape mode. I don't think this is related to branch as see it happening on other pages too. For example on https://www.adobe.com/creativecloud.html
Screen Shot 2024-04-23 at 8 27 37 PM

This might need fix in gnav and doesn't appear to be related to this PR.

cc @sigadamvenkata  @asonnalagi

**Review by suhjainadobe — APPROVED** [review]

**Comment by spadmasa** [comment]
Validation done in the below url for the gnav sticky :
https://stickygnav--milo--adobecom.hlx.page/drafts/ruchika/branch-io/branch-io-page1?martech=off
https://main--cc--adobecom.hlx.page/drafts/ruchika/mobile-app-banner?milolibs=stickygnav&martech=off
image
image

image

image
image
image
image

image

image
image


on gnav issue reported ther issue is handled sepratley via PR https://github.com/adobecom/milo/pull/2185

**Review by mokimo — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]
FYI, this is another puzzle piece for this logic - https://github.com/adobecom/milo/pull/2185

In the sense that content might get cut off without that fix. @sharmrj, this is one of the scenarios where a CSS-only solution would not have yielded the expected results.

**Review by Blainegunn — APPROVED** [review]

**Pull request merged**
