### PR TITLE
[Release] Stage to Main

### PR DESCRIPTION
**Pull request by 3ch023**
Shipping these PRs to Main:

* https://github.com/adobecom/milo/pull/1929
* https://github.com/adobecom/milo/pull/1940

### CODE REVIEW

**Review by overmyheadandbody — COMMENTED** [review]
(Although I don't agree with it), the process was suggesting one PR at a time. Exceptions could be made for PRs that don't touch the same piece of logic, so reverts could be easily done. Was this the intention here?

The assignment of T1 consumers is still in the works, would we want to manually add them for now based on the Wiki document?

**Review by mokimo — APPROVED** [review]

**Comment by mokimo** [comment]
@3ch023 added a TODO number 5 to gather all the consumers and add a channel

**Comment by honstar** [comment]
> when I started my shift today there was a PR merged to stage, but there was no PR for main which is already a fail in our process.

FYI, auto PR workflow is still pending: #1950

**Comment by sigadamvenkata** [comment]
Both issues have been verified from CC prospective.

1. intl cookie set once you select region and accept locales. PF screen shot below
2. Adobe logo present in Stage CC pages in Gnav. 
thanks @SilviuLCF 

image

@honstar @3ch023 @mokimo

**Comment by 3ch023** [comment]
> > @3ch023 added a TODO number 5 to gather all the consumers and add a channel in the [discussion](https://github.com/orgs/adobecom/discussions/1953)
> 
> Please note that @Blainegunn has created explicit SOT groups that contain all representatives of our T1 consumers, see https://github.com/adobecom/milo/pull/1949/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R6
> 
> I went ahead and added those SOT teams as reviewers.

ohh thx, I didn't realize we could just add a group as a whole. makes it much simpler

**Review by Blainegunn — APPROVED** [review]

**Review by overmyheadandbody — APPROVED** [review]

**Review by echampio-at-adobe — APPROVED** [review]
As far as I can tell, the live CC quiz behaves as it should. The region selector now works on stage to go back and forth between the English quiz on Milo and the other locales in AEM. https://www.stage.adobe.com/creativecloud/plan-recommender/quiz.html

**Review by Dli3 — APPROVED** [review]

**Comment by Dli3** [comment]
Verified on bacom stage. Looks good to me.

**Review by sanrai — APPROVED** [review]

**Pull request merged**
