### PR TITLE
fix(MWPW-138316):scrolling inside an iframe is disabled(with screen break point)

### PR DESCRIPTION
**Pull request by sharath-kannan**
* scrolling inside an iframe is disable as is causes multiple scrollbars to be visible.
* considered the issue caused by the previous fix in i-phones.

Resolves: [MWPW-138316](https://jira.corp.adobe.com/browse/MWPW-138316)

**Test URLs:**
- Before: https://main--cc--adobecom.hlx.live/es/creativecloud/animation/discover?martech=off#animate
- After: https://main--cc--adobecom.hlx.live/es/creativecloud/animation/discover?martech=off&milolibs=MWPW-138316--milo--sharath-kannan#animate

### CODE REVIEW

**Comment by Snehayt** [comment]
Verified the the scrollbar in CC in all browsers (chrome, firefox, edge,brave) and devices(android, iphone, ipad, mac) and it works as expected.

https://main--cc--adobecom.hlx.live/es/creativecloud/animation/discover?martech=off&milolibs=MWPW-138316--milo--sharath-kannan#animate
image
image
image
image




Can you please verify the scrollbar from your side too and confirm?
 @https://github.com/JFernandezAdobe ,Reuben Royce Noronha , Dennis Li

**Comment by Dli3** [comment]
@sharath-kannan I've verified on bacom. Looks good to me.

**Comment by Roycethan** [comment]
these issues can occur for different screen resolutions and content heights.
So For TWP modals then [Myroslava Fedas](https://jira.corp.adobe.com/secure/ViewProfile.jspa?name=cod07261) has implemented
style: height-fit-content which needs authoring this style in doc for TWP modals which will allow height auto adjustment and also should resolve this. Similar one to refer : https://jira.corp.adobe.com/browse/MWPW-142798

**Comment by sharath-kannan** [comment]
> these issues can occur for different screen resolutions and content heights. So For TWP modals then [Myroslava Fedas](https://jira.corp.adobe.com/secure/ViewProfile.jspa?name=cod07261) has implemented style: height-fit-content which needs authoring this style in doc for TWP modals which will allow height auto adjustment and also should resolve this. Similar one to refer : https://jira.corp.adobe.com/browse/MWPW-142798

I am aware of that fix, but i don't think it resolves the double scroll bar issue.
I have verified that with the urls given below(These include height-fit-content)
https://main--cc--adobecom.hlx.page/fi/drafts/syt/raster#modal1
https://main--cc--adobecom.hlx.page/fi/drafts/syt/raster?milolibs=MWPW-138316--milo--sharath-kannan#modal1

**Review by mirafedas — APPROVED** [review]

**Comment by Snehayt** [comment]
Hi @sharath-kannan ,
The modal is loading empty for the fix you've given.It will impact all the cloud pages once fix merges to the main.Since all the purchase flows happens via modal ,this fix will not work.
Fix is to be given such that it does not affect any modals across all cloud pages.

image

**Comment by mirafedas** [comment]
Hi @Snehayt please try adding the class 'height-fit-content' to the modal, this should fix the issue.

**Comment by sigadamvenkata** [comment]
hi @mirafedas , when this fix goes to main branch it will break most of the locale price models. and we don't know now many pages has these sort models and needs re-authoring across clouds. 

see the below product page which is LIVE when fix applied to it
URL: https://main--cc--adobecom.hlx.live/de/creativecloud/animation/discover?martech=off&milolibs=MWPW-138316--milo--sharath-kannan#animate

image

@Dli3 @Snehayt @JFernandezAdobe @salonijain3 @Roycethan

**Comment by sharath-kannan** [comment]
> @sigadamvenkata yes, I am aware that modal styles would not work properly without the 'height-fit-content' class set by authors. When introducing that change I was not aware it could be a problem for authors to add these classes. Here is a solution: #1946 . I included changes made by Sharath in this PR, and changed the code so that now the 'height-fit-content' class will be set automatically for all the modals that render Trial with Purchase pages (e.g. https://www.adobe.com/mini-plans/photoshop.html?mid=ft&amp;web=1&amp;pint=Photoshop ). This should fix the modal styles issues we have now and keep the automatic height adjustment working for TwP pages. I guess when my PR is approved and verified, if Sharath doesn't mind, we can close this PR and merge only #1946, as it includes both his and my changes. @sharath-kannan do you agree?
> 
> https://main--cc--adobecom.hlx.live/de/creativecloud/animation/discover?martech=off&milolibs=mwpw-142798-autoset-height-fit-content--milo--mirafedas#animate

Yes, we could close this PR if [#1946](https://github.com/adobecom/milo/pull/1946) is merged.
Thanks.

**Review by mokimo — APPROVED** [review]

**Review by mokimo — CHANGES_REQUESTED** [review]
Meant to request changes as long as the issues mentioned in the comments exist. Either this is fixed here or in https://github.com/adobecom/milo/pull/1946 seems like 1946 will be the one.

**Comment by sharath-kannan** [comment]
> Meant to request changes as long as the issues mentioned in the comments exist. Either this is fixed here or in #1946 seems like 1946 will be the one.

yes,I'm waiting for #1946 to be merged so that i can close this PR.

**Pull request closed without merging**
