### PR TITLE
Fix: Load gnav search files only if it is authored

### PR DESCRIPTION
**Pull request by bandana147**
* Removing unnecessary loading of gnav search JS and CSS files.

Resolves: [MWPW-154608](https://jira.corp.adobe.com/browse/MWPW-154608)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.live/drafts/blaishram/gnav-search-page?martech=off
- After: https://gnav-search--milo--bandana147.hlx.live/drafts/blaishram/gnav-search-page?martech=off

### CODE REVIEW

**Review by sharmrj — APPROVED** [review]

**Review by salonijain3 — APPROVED** [review]

**Review by Deva309 — APPROVED** [review]

**Review by nishantka — APPROVED** [review]

**Comment by sigadamvenkata** [comment]
Issue verfied with given branch libraries. if search is not authored in Gnav then respective 'gnav-search.js' / 'gnav-search.css' files doesn't load.

without fix : https://stage--cc--adobecom.hlx.live/products/firefly 
After Fix : https://stage--cc--adobecom.hlx.live/products/firefly?milolibs=gnav-search--milo--bandana147
image
@bandana147 @salonijain3

**Review by overmyheadandbody — APPROVED** [review]

**Review by mokimo — APPROVED** [review]

**Review by mokimo — APPROVED** [review]

**Comment by mokimo** [comment]
Is search even still used anywhere? You might be able to remove all the search related logic. 
You could also add lana logs to find out _where/if_ search is still used

**Comment by overmyheadandbody** [comment]
@mokimo - I had the same question in the past, but didn't get a reply. I'm assuming that this PR comes out of a need from somewhere where search is used, but it would be great to understand what that use-case is. CC: @bandana147

**Comment by bandana147** [comment]
Yes, that is our next step. We will remove it once we confirm that it is not required anywhere else.

**Review by sonawanesnehal3 — APPROVED** [review]

**Comment by sigadamvenkata** [comment]
regression on stage
image

**Pull request merged**
