### PR TITLE
[MWPW-140071] Caas-Marquee Milo library block

### PR DESCRIPTION
**Pull request by cmiqueo**
Initial commit for the new CaaS Marquee block

This block allows to create and send to CaaS marquees content that will later be rendered on the page by the CaaSMarqueeViewer (https://jira.corp.adobe.com/browse/MWPW-141651)

Resolves: [MWPW-140071](https://jira.corp.adobe.com/browse/MWPW-140071)

**Test URLs:**
https://milo.adobe.com/tools/caas
https://caas-marquee.adobe.com/tools/caas

### CODE REVIEW

**Comment by rgclayton** [comment]
Are we just doing a sanity check on the initial code? Or should we be able to test or see any thing work yet?

**Comment by cmiqueo** [comment]
> Are we just doing a sanity check on the initial code? Or should we be able to test or see any thing work yet?

@rgclayton I'm not sure how to really test it until it is merged. 
So far, for the rendering part, I've been using my localhost as in: https://localhost.corp.adobe.com:3000/drafts/cmiqueo/caas-marquee
And for the send to caas, I was using source overrides

**Comment by sanrai** [comment]
@cmiqueo you can close this PR as these changes have been incorporated in the following PR:
https://github.com/adobecom/milo/pull/1829

**Comment by cmiqueo** [comment]
No longer needed

**Pull request closed without merging**
