### PR TITLE
MWPW-137106: ost promo, href origin fixes 

### PR DESCRIPTION
**Pull request by Axelcureno**
Fixes:
- Offer Selector Tool promotion code parameter value mismatching in generated URLs.
- location origin for href of generated URLs generating wrong URLs(current code is generating as an example: https://milo.adobe.com/tools/milo.adobe.com/tools/ost?osi=....).

Resolves: [MWPW-137106](https://jira.corp.adobe.com/browse/MWPW-137106)

**Test URLs:**
- Before: https://milo.adobe.com/tools/ost?ref=main&repo=milo&owner=adobecom&host=milo.adobe.com&project=Milo&referrer=https%3A%2F%2Fadobe.sharepoint.com%2F%3Aw%3A%2Fr%2Fsites%2Fadobecom%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B42bda19c-d9f7-4cf3-9c3f-6098bb958528%257D%26action%3Deditnew
- After: https://mwpw-137106--milo--adobecom.hlx.page/tools/ost?osi=Mutn1LYoGojkrcMdCLO7LQlx1FyTHw27ETsfLv0h8DQ&type=price&promo=axelpromo&term=true&seat=false&tax=false&exclusive=true

### CODE REVIEW

**Review by honstar — APPROVED** [review]

**Comment by narcis-radu** [comment]
@Axelcureno - I see some OST related tests failing after your change. Can you please check? 

```
test/blocks/ost/ost.test.js:

 ❌ function "createLinkMarkup" > creates "cta" link > with promo and custom text
      AssertionError: expected null to equal 'test-promo'
        at test/blocks/ost/ost.test.js:28:38
        at Array.forEach (<anonymous>)
        at assertLink (test/blocks/ost/ost.test.js:27:26)
        at o.<anonymous> (test/blocks/ost/ost.test.js:60:7)
```

**Comment by Axelcureno** [comment]
> @Axelcureno - I see some OST related tests failing after your change. Can you please check?
> 
> ```
> test/blocks/ost/ost.test.js:
> 
>  ❌ function "createLinkMarkup" > creates "cta" link > with promo and custom text
>       AssertionError: expected null to equal 'test-promo'
>         at test/blocks/ost/ost.test.js:28:38
>         at Array.forEach (<anonymous>)
>         at assertLink (test/blocks/ost/ost.test.js:27:26)
>         at o.<anonymous> (test/blocks/ost/ost.test.js:60:7)
> ```

Thank you, it's now fixed.

**Review by narcis-radu — APPROVED** [review]

**Review by 3ch023 — APPROVED** [review]

**Review by yesil — APPROVED** [review]

**Comment by afmicka** [comment]
@Axelcureno could you please check the promo functionality? It does not append promo info to the price in the ost on this branch. That would be a regression.

**Comment by Axelcureno** [comment]
> @Axelcureno could you please check the promo functionality? It does not append promo info to the price in the ost on this branch. That would be a regression.

Confirmed with my changes it is working as expected: https://mwpw-139503--milo--adobecom.hlx.page/drafts/nala/features/placeholders/commerce

Screenshot 2023-11-27 at 10 31 07 AM

**Review by vladen — APPROVED** [review]

**Pull request merged**
