### PR TITLE
MWPW-156089: See what's included modal additional white space issue

### PR DESCRIPTION
**Pull request by mirafedas**
This PR implements a feature that allows the modal window to dynamically adjust its height based on the content height of the page loaded within an iFrame. Here’s how it works:

1. **Content Measurement**: The iFrame page measures its content height and sends this information through a `postMessage`. For further details, see [Titan PR](https://git.corp.adobe.com/wcms/titan/pull/3820).

2. **Dynamic Height Handling**: On the Milo side, if the modal has the `dynamic-height` class, it listens for the corresponding `postMessage` from the iFrame.

3. **Height Adjustment Logic**:
   - **Desktop**: If the modal’s height exceeds the iFrame’s content height, the modal will automatically adjust to match.
   - **Mobile**: The modal height will always be set to 100% to ensure a consistent user experience.

**Note for Authors**: Please ensure to apply the `xl-size` class to modals that include "What's Included" content for proper styling.
**Note for QA**: Please ensure the ModHeader is enabled to avoid the CORS-related issues and add `https://www.qa02.adobe.com` in plugin settings (until Titan PR is merged the change is deployed to QA02 env from my feature branch):
`frame-ancestors: 'self' https://*.adobe.com http://localhost:6456/ https://www.qa02.adobe.com https://*.hlx.page https://*.hlx.live`

Resolves: [MWPW-156089](https://jira.corp.adobe.com/browse/MWPW-156089)

**Test URLs:**
- Before: https://main--milo--mirafedas.hlx.page/drafts/mirafedas/all-modals?martech=off&georouting=off#qa02
- After: https://mwpw-156089-iframe-height-adjustment--milo--mirafedas.hlx.page/drafts/mirafedas/all-modals?martech=off&georouting=off#qa02

### CODE REVIEW

**Review by yesil — APPROVED** [review]
on large screens, it looks like the width also requires some styles.

**Comment by mirafedas** [comment]
@yesil thank you for the review! On bigger screens styles look ok to me (see screenshot), is there anything I did not notice?
Screenshot 2024-11-04 at 12 43 23

**Comment by mirafedas** [comment]
@yesil thank you, I restricted the width for large screens 👍

**Review by npeltier — APPROVED** [review]
lgtm

**Review by Axelcureno — APPROVED** [review]

**Comment by afmicka** [comment]
@mirafedas something is happening with the logo in the gnav on your branch. Could you please check?
https://main--homepage--adobecom.hlx.page/uk/homepage/index-loggedout?milolibs=mwpw-156089-iframe-height-adjustment--milo--mirafedas

https://main--cc--adobecom.hlx.live/pl/creativecloud?milolibs=mwpw-156089-iframe-height-adjustment--milo--mirafedas
Screenshot 2024-11-14 at 13 38 53
Screenshot 2024-11-14 at 13 38 36

**Comment by afmicka** [comment]
@mirafedas also the links in the merch card are not underlined with your changes 
https://main--cc--adobecom.hlx.live/creativecloud/file-types/image/comparison?milolibs=mwpw-156089-iframe-height-adjustment--milo--mirafedas
Screenshot 2024-11-14 at 13 51 17


with `milolibs=stage` they still are: 
https://main--cc--adobecom.hlx.live/creativecloud/file-types/image/comparison?milolibs=stage
Screenshot 2024-11-14 at 13 53 36

**Pull request merged**
