### PR TITLE
MWPW-157701 [Fast-follow] - Add'l Pill updates

### PR DESCRIPTION
**Pull request by elan-tbx**
* While the latest updates to the Pill Notification variant (released in #2775) meet the requirements for release, there are still some use-cases that need to be addressed. Marked as high-priority due to the fact that these bugs hinder DC's publishing ability on new, live updates to published pages that use this block (sorry if I'm jumping the gun here, happy to downgrade if necessary). From the JIRA ticket:
  * There is a white background added to `flexible` styled Pill Notifications. -- fixed ✅ 
  * The default drop-shadow also does not look great on top of certain colors. -- there is an ongoing discussion amongst the designers around what a better value would be, but for now this PR adds a `no-shadow` option so authors can remove it if necessary
  * The block does not produce the expected results when, for example, `max-width-8` is applied to it, or its parent. -- fixed ✅ the `max-width-*` styles apply specifically to the `.foreground` elements within Milo blocks, which works for most use-cases, but does not achieve the expected result (Pill itself adheres to defined grid widths) in this specific block variant.

Resolves: [MWPW-157701](https://jira.corp.adobe.com/browse/MWPW-157701)

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/ebartholomew/fragments/acrobat-individuals-copy?martech=off
- After: https://ebartholomew-mwpw-157701-pill-fast-follow--milo--adobecom.hlx.page/drafts/ebartholomew/fragments/acrobat-individuals-copy?martech=off

DC (where these issues were first reported):
- Before: https://main--dc--adobecom.hlx.page/drafts/ebartholomew/acrobat-individuals?martech=off
- After: https://main--dc--adobecom.hlx.page/drafts/ebartholomew/acrobat-individuals?martech=off&milolibs=ebartholomew-mwpw-157701-pill-fast-follow

### CODE REVIEW

**Review by meganthecoder — APPROVED** [review]

**Comment by meganthecoder** [comment]
@elan-tbx lgtm, just need to check on failing nala tests

**Comment by elan-tbx** [comment]
@meganthecoder thank you!

Yeah, I'm not sure why but the NALA failures all seem to be related to the Video block for some reason...

Screenshot 2024-09-04 at 2 34 01 PM

To be honest, this PR only affects 1 file and it is CSS, so I'm not 100% sure the tag is necessary here... but probably good to raise the issue of those errors either way so they don't have an effect on other PRs 😬

**Review by overmyheadandbody — APPROVED** [review]

**Comment by skumar09** [comment]
> @meganthecoder thank you!
> 
> Yeah, I'm not sure why but the NALA failures all seem to be related to the Video block for some reason...
> 
> Screenshot 2024-09-04 at 2 34 01 PM
> 
> To be honest, this PR only affects 1 file and it is CSS, so I'm not 100% sure the `run-nala` tag is necessary here... but probably good to raise the issue of those errors either way so they don't have an effect on other PRs 😬

@elan-tbx : There is an update to Video Block (YouTube from another PR, i am checking  on the same and will update the nala tests.

**Review by ryanmparrish — APPROVED** [review]

**Review by NadiiaSokolova — APPROVED** [review]
Verified. Ready for Stage.
Testing details https://jira.corp.adobe.com/browse/MWPW-157701

**Pull request merged**
