### PR TITLE
MWPW-135675 Fix marquee video

### PR DESCRIPTION
**Pull request by chrischrischris**
Update marquee videos to work with new inline fragments ( #1242 )

Resolves: [MWPW-135675](https://jira.corp.adobe.com/browse/MWPW-135675)

Homepage test url:
- Before: https://homepage-brick--homepage--adobecom.hlx.live/homepage/index-loggedout
- After: https://homepage-brick--homepage--adobecom.hlx.live/homepage/index-loggedout?milolibs=marqinlinefrag

**Test URLs:**
- Before: https://main--milo--adobecom.hlx.page/drafts/tat28144/regional-edits/marqueevideo?martech=off
- After: https://marqinlinefrag--milo--adobecom.hlx.page/drafts/tat28144/regional-edits/marqueevideo?martech=off

### CODE REVIEW

**Review by Sartxi — APPROVED** [review]

**Review by JasonHowellSlavin — COMMENTED** [review]
Looks good to me. Should we add some tests to cover the functionality?

**Comment by JasonHowellSlavin** [comment]
https://github.com/adobecom/milo/pull/1258 touching some of the same code as @seanchoi-dev's PR too. May want to meet in the middle?

**Review by vgoodric — APPROVED** [review]
Checked against https://main--homepage--adobecom.hlx.page/homepage/drafts/vgoodrich/marquee-video-demo?milolibs=marqinlinefrag

**Comment by vgoodric** [comment]
> #1258 touching some of the same code as @seanchoi-dev's PR too. May want to meet in the middle?

@seanchoi-dev 's update is an improvement to lighthouse scores, but not a blocker for homepage migration like this PR.  I'd like to merge this PR and then have Sean adjust his code as needed.  But we need this one merged today.

**Pull request merged**
