### PR TITLE
Marquee block design updates and ESLint issues resolved

### PR DESCRIPTION
**Pull request by ryanmparrish**
* Addressed the Marquee block `center` variant naming convention (`centered` is deprecated but still backwards compatible)
* Adjusted the Marquee block `quiet` variant to have a 600px default content width
* Adjusted the Marquee block `split, one-third` variant to be split 50/50 on tablet viewport
* Fixed all linting issues in `marquee.css` and `marquee.js` files

Resolves: 
 - [MWPW-131806](https://jira.corp.adobe.com/browse/MWPW-131806)
 - [MWPW-131560](https://jira.corp.adobe.com/browse/MWPW-131560)

**Test URLs:**

**Drafts**
- Before: [https://main-milo--adobecom.hlx.page/drafts/rparrish/marquee?martech=off](https://main-milo--adobecom.hlx.page/drafts/rparrish/marquee?martech=off)
- After: [https://rparrish-marquee-fix--milo--adobecom.hlx.page/drafts/rparrish/marquee?martech=off](https://rparrish-marquee-fix--milo--adobecom.hlx.page/drafts/rparrish/marquee?martech=off)

**Libs**
- Before: [https://main--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off](https://main--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off)
- After: [https://rparrish-marquee-fix--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off](https://rparrish-marquee-fix--milo--adobecom.hlx.page/docs/library/blocks/marquee?martech=off)

### CODE REVIEW

**Review by Sartxi — APPROVED** [review]
LGTM

**Review by elan-tbx — APPROVED** [review]
Looks great! Confirming that this does not step on the toes of #861

**Comment by ryanmparrish** [comment]
FYI, Im seeing some inconsistencies w/ some of the headline sizes. Im addressing now and will update.

**Comment by ryanmparrish** [comment]
FYI. This above mentioned type issues are fixed and looks GTG on my end.

**Review by Sartxi — APPROVED** [review]

**Review by elan-tbx — APPROVED** [review]

**Pull request merged**
