### PR TITLE
[Release] Stage to Main

### PR DESCRIPTION
**Pull request by Blainegunn**
- https://github.com/adobecom/milo/pull/2081
- https://github.com/adobecom/milo/pull/2085
- https://github.com/adobecom/milo/pull/1945
- https://github.com/adobecom/milo/pull/2053
- https://github.com/adobecom/milo/pull/2113
- https://github.com/adobecom/milo/pull/2052
- https://github.com/adobecom/milo/pull/2057
- https://github.com/adobecom/milo/pull/2062
- https://github.com/adobecom/milo/pull/2063
- https://github.com/adobecom/milo/pull/2067

### CODE REVIEW

**Review by rgclayton — APPROVED** [review]
https://github.com/adobecom/milo/pull/2062 looks good!

**Review by ryanmparrish — APPROVED** [review]

**Review by Roycethan — APPROVED** [review]

**Review by JackySun9 — APPROVED** [review]

**Comment by TsayAdobe** [comment]
@yesil @Axelcureno FYI, observe that `<slot name="icons">` is added and push down a merch-card content a bit. I think it's OK.
Before: https://stage--dc--adobecom.hlx.live/dc-shared/fragments/shared-fragments/pricing-pods/standard-pro-know
After: https://stage--dc--adobecom.hlx.live/dc-shared/fragments/shared-fragments/pricing-pods/standard-pro-know?milolibs=stage
price diff

**Comment by yesil** [comment]
@TsayAdobe thanks for reporting. I think this is ok, we can revisit this in a future PR if needed.
@afmicka wdyt?

**Comment by afmicka** [comment]
> https://stage--dc--adobecom.hlx.live/dc-shared/fragments/shared-fragments/pricing-pods/standard-pro-know

@yesil @TsayAdobe I would also say it is ok. We can follow up on this if needed.

**Review by NadiiaSokolova — APPROVED** [review]

**Review by Dli3 — APPROVED** [review]

**Pull request merged**
